### ISSUE TITLE
Cannot convert from UUID to JSON in H2's JSON_OBJECT() and related functions

### ISSUE THREAD

**Issue by gilinykh** [jOOQ/jOOQ#10769]
### Expected behavior
Query result containing records with UUID successfully mapped to DTO via JSON document.

### Actual behavior
Exception is thrown when JOOQ attempts to map the record:
```
org.springframework.dao.DataIntegrityViolationException: jOOQ; SQL [select json_object(key ? value "PARENT"."ID", key ? value "PARENT"."NAME", key ? value json_arrayagg(json_object(key ? value "CHILD"."PARENT_ID", key ? value "CHILD"."NAME") order by "PARENT"."NAME")) from "PARENT" left outer join "CHILD" on "CHILD"."PARENT_ID" = "PARENT"."ID" group by "PARENT"."ID", "PARENT"."NAME" order by "PARENT"."ID", "PARENT"."NAME"]; Data conversion error converting "UUID to JSON"
Data conversion error converting "UUID to JSON"; SQL statement:
select json_object(key ? value "PARENT"."ID", key ? value "PARENT"."NAME", key ? value json_arrayagg(json_object(key ? value "CHILD"."PARENT_ID", key ? value "CHILD"."NAME") order by "PARENT"."NAME")) from "PARENT" left outer join "CHILD" on "CHILD"."PARENT_ID" = "PARENT"."ID" group by "PARENT"."ID", "PARENT"."NAME" order by "PARENT"."ID", "PARENT"."NAME" [22018-200]; nested exception is org.h2.jdbc.JdbcSQLDataException: Data conversion error converting "UUID to JSON"
Data conversion error converting "UUID to JSON"; SQL statement:
select json_object(key ? value "PARENT"."ID", key ? value "PARENT"."NAME", key ? value json_arrayagg(json_object(key ? value "CHILD"."PARENT_ID", key ? value "CHILD"."NAME") order by "PARENT"."NAME")) from "PARENT" left outer join "CHILD" on "CHILD"."PARENT_ID" = "PARENT"."ID" group by "PARENT"."ID", "PARENT"."NAME" order by "PARENT"."ID", "PARENT"."NAME" [22018-200]

	at org.jooq_3.14.0.DEFAULT.debug(Unknown Source)
	at org.springframework.jdbc.support.SQLStateSQLExceptionTranslator.doTranslate(SQLStateSQLExceptionTranslator.java:104)
	at org.springframework.jdbc.support.AbstractFallbackSQLExceptionTranslator.translate(AbstractFallbackSQLExceptionTranslator.java:72)
	at org.springframework.boot.autoconfigure.jooq.JooqExceptionTranslator.translate(JooqExceptionTranslator.java:92)
	at org.springframework.boot.autoconfigure.jooq.JooqExceptionTranslator.handle(JooqExceptionTranslator.java:81)
	at org.springframework.boot.autoconfigure.jooq.JooqExceptionTranslator.exception(JooqExceptionTranslator.java:55)
	at org.jooq.impl.ExecuteListeners.exception(ExecuteListeners.java:274)
	at org.jooq.impl.AbstractQuery.execute(AbstractQuery.java:390)
	at org.jooq.impl.AbstractResultQuery.fetch(AbstractResultQuery.java:333)
	at org.jooq.impl.AbstractResultQuery.fetchInto(AbstractResultQuery.java:1545)
	at org.jooq.impl.SelectImpl.fetchInto(SelectImpl.java:3936)
	at com.example.uuidjson.JooqParentRepository.list(JooqParentRepository.java:38)
	at com.example.uuidjson.JooqParentRepository$$FastClassBySpringCGLIB$$93c0a175.invoke(<generated>)
	at org.springframework.cglib.proxy.MethodProxy.invoke(MethodProxy.java:218)
	at org.springframework.aop.framework.CglibAopProxy$CglibMethodInvocation.invokeJoinpoint(CglibAopProxy.java:771)
	at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:163)
	at org.springframework.aop.framework.CglibAopProxy$CglibMethodInvocation.proceed(CglibAopProxy.java:749)
	at org.springframework.transaction.interceptor.TransactionAspectSupport.invokeWithinTransaction(TransactionAspectSupport.java:367)
	at org.springframework.transaction.interceptor.TransactionInterceptor.invoke(TransactionInterceptor.java:118)
	at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:186)
	at org.springframework.aop.framework.CglibAopProxy$CglibMethodInvocation.proceed(CglibAopProxy.java:749)
	at org.springframework.aop.framework.CglibAopProxy$DynamicAdvisedInterceptor.intercept(CglibAopProxy.java:691)
	at com.example.uuidjson.JooqParentRepository$$EnhancerBySpringCGLIB$$92b1c668.list(<generated>)
	at com.example.uuidjson.JooqParentRepositoryTest.parentWithChildrenFetched(JooqParentRepositoryTest.java:25)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:564)
	at org.junit.platform.commons.util.ReflectionUtils.invokeMethod(ReflectionUtils.java:686)
	at org.junit.jupiter.engine.execution.MethodInvocation.proceed(MethodInvocation.java:60)
	at org.junit.jupiter.engine.execution.InvocationInterceptorChain$ValidatingInvocation.proceed(InvocationInterceptorChain.java:131)
	at org.junit.jupiter.engine.extension.TimeoutExtension.intercept(TimeoutExtension.java:149)
	at org.junit.jupiter.engine.extension.TimeoutExtension.interceptTestableMethod(TimeoutExtension.java:140)
	at org.junit.jupiter.engine.extension.TimeoutExtension.interceptTestMethod(TimeoutExtension.java:84)
	at org.junit.jupiter.engine.execution.ExecutableInvoker$ReflectiveInterceptorCall.lambda$ofVoidMethod$0(ExecutableInvoker.java:115)
	at org.junit.jupiter.engine.execution.ExecutableInvoker.lambda$invoke$0(ExecutableInvoker.java:105)
	at org.junit.jupiter.engine.execution.InvocationInterceptorChain$InterceptedInvocation.proceed(InvocationInterceptorChain.java:106)
	at org.junit.jupiter.engine.execution.InvocationInterceptorChain.proceed(InvocationInterceptorChain.java:64)
	at org.junit.jupiter.engine.execution.InvocationInterceptorChain.chainAndInvoke(InvocationInterceptorChain.java:45)
	at org.junit.jupiter.engine.execution.InvocationInterceptorChain.invoke(InvocationInterceptorChain.java:37)
	at org.junit.jupiter.engine.execution.ExecutableInvoker.invoke(ExecutableInvoker.java:104)
	at org.junit.jupiter.engine.execution.ExecutableInvoker.invoke(ExecutableInvoker.java:98)
	at org.junit.jupiter.engine.descriptor.TestMethodTestDescriptor.lambda$invokeTestMethod$6(TestMethodTestDescriptor.java:212)
	at org.junit.platform.engine.support.hierarchical.ThrowableCollector.execute(ThrowableCollector.java:73)
	at org.junit.jupiter.engine.descriptor.TestMethodTestDescriptor.invokeTestMethod(TestMethodTestDescriptor.java:208)
	at org.junit.jupiter.engine.descriptor.TestMethodTestDescriptor.execute(TestMethodTestDescriptor.java:137)
	at org.junit.jupiter.engine.descriptor.TestMethodTestDescriptor.execute(TestMethodTestDescriptor.java:71)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.lambda$executeRecursively$5(NodeTestTask.java:135)
	at org.junit.platform.engine.support.hierarchical.ThrowableCollector.execute(ThrowableCollector.java:73)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.lambda$executeRecursively$7(NodeTestTask.java:125)
	at org.junit.platform.engine.support.hierarchical.Node.around(Node.java:135)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.lambda$executeRecursively$8(NodeTestTask.java:123)
	at org.junit.platform.engine.support.hierarchical.ThrowableCollector.execute(ThrowableCollector.java:73)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.executeRecursively(NodeTestTask.java:122)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.execute(NodeTestTask.java:80)
	at java.base/java.util.ArrayList.forEach(ArrayList.java:1510)
	at org.junit.platform.engine.support.hierarchical.SameThreadHierarchicalTestExecutorService.invokeAll(SameThreadHierarchicalTestExecutorService.java:38)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.lambda$executeRecursively$5(NodeTestTask.java:139)
	at org.junit.platform.engine.support.hierarchical.ThrowableCollector.execute(ThrowableCollector.java:73)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.lambda$executeRecursively$7(NodeTestTask.java:125)
	at org.junit.platform.engine.support.hierarchical.Node.around(Node.java:135)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.lambda$executeRecursively$8(NodeTestTask.java:123)
	at org.junit.platform.engine.support.hierarchical.ThrowableCollector.execute(ThrowableCollector.java:73)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.executeRecursively(NodeTestTask.java:122)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.execute(NodeTestTask.java:80)
	at java.base/java.util.ArrayList.forEach(ArrayList.java:1510)
	at org.junit.platform.engine.support.hierarchical.SameThreadHierarchicalTestExecutorService.invokeAll(SameThreadHierarchicalTestExecutorService.java:38)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.lambda$executeRecursively$5(NodeTestTask.java:139)
	at org.junit.platform.engine.support.hierarchical.ThrowableCollector.execute(ThrowableCollector.java:73)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.lambda$executeRecursively$7(NodeTestTask.java:125)
	at org.junit.platform.engine.support.hierarchical.Node.around(Node.java:135)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.lambda$executeRecursively$8(NodeTestTask.java:123)
	at org.junit.platform.engine.support.hierarchical.ThrowableCollector.execute(ThrowableCollector.java:73)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.executeRecursively(NodeTestTask.java:122)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.execute(NodeTestTask.java:80)
	at org.junit.platform.engine.support.hierarchical.SameThreadHierarchicalTestExecutorService.submit(SameThreadHierarchicalTestExecutorService.java:32)
	at org.junit.platform.engine.support.hierarchical.HierarchicalTestExecutor.execute(HierarchicalTestExecutor.java:57)
	at org.junit.platform.engine.support.hierarchical.HierarchicalTestEngine.execute(HierarchicalTestEngine.java:51)
	at org.junit.platform.launcher.core.DefaultLauncher.execute(DefaultLauncher.java:248)
	at org.junit.platform.launcher.core.DefaultLauncher.lambda$execute$5(DefaultLauncher.java:211)
	at org.junit.platform.launcher.core.DefaultLauncher.withInterceptedStreams(DefaultLauncher.java:226)
	at org.junit.platform.launcher.core.DefaultLauncher.execute(DefaultLauncher.java:199)
	at org.junit.platform.launcher.core.DefaultLauncher.execute(DefaultLauncher.java:132)
	at com.intellij.junit5.JUnit5IdeaTestRunner.startRunnerWithArgs(JUnit5IdeaTestRunner.java:71)
	at com.intellij.rt.junit.IdeaTestRunner$Repeater.startRunnerWithArgs(IdeaTestRunner.java:33)
	at com.intellij.rt.junit.JUnitStarter.prepareStreamsAndStart(JUnitStarter.java:220)
	at com.intellij.rt.junit.JUnitStarter.main(JUnitStarter.java:53)
Caused by: org.h2.jdbc.JdbcSQLDataException: Data conversion error converting "UUID to JSON"
Data conversion error converting "UUID to JSON"; SQL statement:
select json_object(key ? value "PARENT"."ID", key ? value "PARENT"."NAME", key ? value json_arrayagg(json_object(key ? value "CHILD"."PARENT_ID", key ? value "CHILD"."NAME") order by "PARENT"."NAME")) from "PARENT" left outer join "CHILD" on "CHILD"."PARENT_ID" = "PARENT"."ID" group by "PARENT"."ID", "PARENT"."NAME" order by "PARENT"."ID", "PARENT"."NAME" [22018-200]
	at org.h2.message.DbException.getJdbcSQLException(DbException.java:457)
	at org.h2.message.DbException.getJdbcSQLException(DbException.java:429)
	at org.h2.message.DbException.get(DbException.java:205)
	at org.h2.message.DbException.get(DbException.java:181)
	at org.h2.value.Value.getDataConversionError(Value.java:1504)
	at org.h2.value.Value.convertToJson(Value.java:1439)
	at org.h2.value.Value.convertTo(Value.java:861)
	at org.h2.value.Value.convertTo(Value.java:737)
	at org.h2.expression.function.Function.jsonObjectAppend(Function.java:2368)
	at org.h2.expression.function.Function.jsonObject(Function.java:2351)
	at org.h2.expression.function.Function.getSimpleValue(Function.java:1153)
	at org.h2.expression.function.Function.getValueWithArgs(Function.java:1274)
	at org.h2.expression.function.Function.getValue(Function.java:672)
	at org.h2.expression.aggregate.Aggregate.updateAggregate(Aggregate.java:205)
	at org.h2.expression.aggregate.AbstractAggregate.updateAggregate(AbstractAggregate.java:280)
	at org.h2.expression.analysis.DataAnalysisOperation.updateAggregate(DataAnalysisOperation.java:252)
	at org.h2.expression.function.Function.updateAggregate(Function.java:3049)
	at org.h2.command.dml.Select.updateAgg(Select.java:545)
	at org.h2.command.dml.Select.gatherGroup(Select.java:525)
	at org.h2.command.dml.Select.queryGroup(Select.java:487)
	at org.h2.command.dml.Select.queryWithoutCache(Select.java:839)
	at org.h2.command.dml.Query.queryWithoutCacheLazyCheck(Query.java:201)
	at org.h2.command.dml.Query.query(Query.java:489)
	at org.h2.command.dml.Query.query(Query.java:451)
	at org.h2.command.CommandContainer.query(CommandContainer.java:285)
	at org.h2.command.Command.executeQuery(Command.java:195)
	at org.h2.jdbc.JdbcPreparedStatement.execute(JdbcPreparedStatement.java:233)
	at org.jooq.tools.jdbc.DefaultPreparedStatement.execute(DefaultPreparedStatement.java:214)
	at org.jooq.impl.Tools.executeStatementAndGetFirstResultSet(Tools.java:4186)
	at org.jooq.impl.AbstractResultQuery.execute(AbstractResultQuery.java:279)
	at org.jooq.impl.AbstractQuery.execute(AbstractQuery.java:375)
	... 79 more
```

### Steps to reproduce the problem

1. Create table with UUID as primary key:
```
create table parent(
    id UUID constraint pk_parent_id primary key,
    name varchar(100)
);
```

2. Run code generation, check that generated field is of UUID type:
```
public final TableField<ParentRecord, UUID> ID = createField(DSL.name("ID"), SQLDataType.UUID.nullable(false), this, "");
```

3. Create target DTO for record mapper:
```
@Getter
@RequiredArgsConstructor
public class Parent {
    private final UUID id;
    private final String name;
    private final Collection<Child> children;
}
```

4. Run a query mapping its result into DTO using JSON as described here: https://blog.jooq.org/2020/10/09/nesting-collections-with-jooq-3-14s-sql-xml-or-sql-json-support/
```
dsl.select(
                jsonObject(
                        jsonEntry("id", PARENT.ID),
                        jsonEntry("name", PARENT.NAME),
                        jsonEntry("children", jsonArrayAgg(
                                jsonObject(
                                        jsonEntry("parentId", CHILD.PARENT_ID),
                                        jsonEntry("name", CHILD.NAME)
                                )
                        ).orderBy(PARENT.NAME))
                )
        )
                .from(PARENT)
                .leftJoin(CHILD).on(CHILD.PARENT_ID.eq(PARENT.ID))
                .groupBy(PARENT.ID, PARENT.NAME)
                .orderBy(PARENT.ID, PARENT.NAME)
                .fetchInto(Parent.class);
```

### Versions

- jOOQ: 3.14.0
- Java: 11
- Database: h2
- OS: Windows
- JDBC Driver: org.h2.Driver

**Comment by gilinykh** [comment]
Here's a reproducer, just run `mvn test`:

[uuidjson.zip](https://github.com/jOOQ/jOOQ/files/5414137/uuidjson.zip)

**Comment by katzyn** [comment]
H2 doesn't support direct conversion from UUID to JSON by itself, so it doesn't look like an issue of jOOQ. It looks like you need an explicit cast to `CHARACTER VARYING` or to `CHARACTER(36)` around UUID values.

**Comment by lukaseder** [comment]
Thanks for your report, @gilinykh. I can reproduce the problem.

Thanks a lot for chiming in, @katzyn 

> H2 doesn't support direct conversion from UUID to JSON by itself, so it doesn't look like an issue of jOOQ.

jOOQ tends to transparently "fix" these things, so I think we can consider this a jOOQ issue. The conversion seems obvious in this case, both from `UUID` to `JSON` and in the end from `JSON` to `UUID`

**Comment by katzyn** [comment]
Hypothetically H2 can also support such conversion directly, but with all special data types the big question is in expected representation of values in JSON, they aren't standardized in any way.

**Comment by lukaseder** [comment]
Yes, indeed. A `UUID` could be an `int128` or a `character(36)`. A `TIMESTAMP` could be a `int64` (unix timestamp with second or millisecond precision) or a `character(<too lazy to count>)`.

I tend to prefer unambiguous encodings, which are mostly strings. The `UUID` string encoding is specified very clearly: https://tools.ietf.org/html/rfc4122, so this is a good candidate. With `TIMESTAMP`, I'd use the SQL timestamp literal encoding (without a `T`), by default, although that is not very JSON friendly, which might expect the ISO encoding (with a `T`), so here we go :)

**Comment by lukaseder** [comment]
For the record, PostgreSQL supports this just fine:

```sql
select json_build_object('uuid', 'f43f8fdf-463a-45e1-b869-00312c98fd18'::uuid)
```

Producing:

```
json_build_object                                |
-------------------------------------------------|
{"uuid" : "f43f8fdf-463a-45e1-b869-00312c98fd18"}|
```

**Comment by lukaseder** [comment]
Fixed in 3.15.0. Backport scheduled for 3.14.1 (#10772).

Thanks again for your report!

**Comment by gilinykh** [comment]
@lukaseder I just checked the issue with jOOQ 3.14.1 where a fix was supposedly provided and for some reason running the same test still reproduces the problem:
```
org.springframework.dao.DataIntegrityViolationException: jOOQ; SQL [select json_object(key ? value "PARENT"."ID", key ? value "PARENT"."NAME", key ? value json_arrayagg(json_object(key ? value "CHILD"."PARENT_ID", key ? value "CHILD"."NAME") order by "PARENT"."NAME")) from "PARENT" left outer join "CHILD" on "CHILD"."PARENT_ID" = "PARENT"."ID" group by "PARENT"."ID", "PARENT"."NAME" order by "PARENT"."ID", "PARENT"."NAME"]; Data conversion error converting "UUID to JSON"
Data conversion error converting "UUID to JSON"; SQL statement:
select json_object(key ? value "PARENT"."ID", key ? value "PARENT"."NAME", key ? value json_arrayagg(json_object(key ? value "CHILD"."PARENT_ID", key ? value "CHILD"."NAME") order by "PARENT"."NAME")) from "PARENT" left outer join "CHILD" on "CHILD"."PARENT_ID" = "PARENT"."ID" group by "PARENT"."ID", "PARENT"."NAME" order by "PARENT"."ID", "PARENT"."NAME" [22018-200]; nested exception is org.h2.jdbc.JdbcSQLDataException: Data conversion error converting "UUID to JSON"
Data conversion error converting "UUID to JSON"; SQL statement:
select json_object(key ? value "PARENT"."ID", key ? value "PARENT"."NAME", key ? value json_arrayagg(json_object(key ? value "CHILD"."PARENT_ID", key ? value "CHILD"."NAME") order by "PARENT"."NAME")) from "PARENT" left outer join "CHILD" on "CHILD"."PARENT_ID" = "PARENT"."ID" group by "PARENT"."ID", "PARENT"."NAME" order by "PARENT"."ID", "PARENT"."NAME" [22018-200]

	at org.jooq_3.14.1.DEFAULT.debug(Unknown Source)
	at org.springframework.jdbc.support.SQLStateSQLExceptionTranslator.doTranslate(SQLStateSQLExceptionTranslator.java:104)
	at org.springframework.jdbc.support.AbstractFallbackSQLExceptionTranslator.translate(AbstractFallbackSQLExceptionTranslator.java:72)
	at org.springframework.boot.autoconfigure.jooq.JooqExceptionTranslator.translate(JooqExceptionTranslator.java:92)
	at org.springframework.boot.autoconfigure.jooq.JooqExceptionTranslator.handle(JooqExceptionTranslator.java:81)
	at org.springframework.boot.autoconfigure.jooq.JooqExceptionTranslator.exception(JooqExceptionTranslator.java:55)
	at org.jooq.impl.ExecuteListeners.exception(ExecuteListeners.java:274)
	at org.jooq.impl.AbstractQuery.execute(AbstractQuery.java:390)
	at org.jooq.impl.AbstractResultQuery.fetch(AbstractResultQuery.java:333)
	at org.jooq.impl.AbstractResultQuery.fetchInto(AbstractResultQuery.java:1545)
	at org.jooq.impl.SelectImpl.fetchInto(SelectImpl.java:3936)
	at com.example.uuidjson.JooqParentRepository.list(JooqParentRepository.java:38)
	at com.example.uuidjson.JooqParentRepository$$FastClassBySpringCGLIB$$93c0a175.invoke(<generated>)
	at org.springframework.cglib.proxy.MethodProxy.invoke(MethodProxy.java:218)
	at org.springframework.aop.framework.CglibAopProxy$CglibMethodInvocation.invokeJoinpoint(CglibAopProxy.java:771)
	at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:163)
	at org.springframework.aop.framework.CglibAopProxy$CglibMethodInvocation.proceed(CglibAopProxy.java:749)
	at org.springframework.transaction.interceptor.TransactionAspectSupport.invokeWithinTransaction(TransactionAspectSupport.java:367)
	at org.springframework.transaction.interceptor.TransactionInterceptor.invoke(TransactionInterceptor.java:118)
	at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:186)
	at org.springframework.aop.framework.CglibAopProxy$CglibMethodInvocation.proceed(CglibAopProxy.java:749)
	at org.springframework.aop.framework.CglibAopProxy$DynamicAdvisedInterceptor.intercept(CglibAopProxy.java:691)
	at com.example.uuidjson.JooqParentRepository$$EnhancerBySpringCGLIB$$c10e02f2.list(<generated>)
	at com.example.uuidjson.JooqParentRepositoryTest.parentWithChildrenFetched(JooqParentRepositoryTest.java:25)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:564)
	at org.junit.platform.commons.util.ReflectionUtils.invokeMethod(ReflectionUtils.java:686)
	at org.junit.jupiter.engine.execution.MethodInvocation.proceed(MethodInvocation.java:60)
	at org.junit.jupiter.engine.execution.InvocationInterceptorChain$ValidatingInvocation.proceed(InvocationInterceptorChain.java:131)
	at org.junit.jupiter.engine.extension.TimeoutExtension.intercept(TimeoutExtension.java:149)
	at org.junit.jupiter.engine.extension.TimeoutExtension.interceptTestableMethod(TimeoutExtension.java:140)
	at org.junit.jupiter.engine.extension.TimeoutExtension.interceptTestMethod(TimeoutExtension.java:84)
	at org.junit.jupiter.engine.execution.ExecutableInvoker$ReflectiveInterceptorCall.lambda$ofVoidMethod$0(ExecutableInvoker.java:115)
	at org.junit.jupiter.engine.execution.ExecutableInvoker.lambda$invoke$0(ExecutableInvoker.java:105)
	at org.junit.jupiter.engine.execution.InvocationInterceptorChain$InterceptedInvocation.proceed(InvocationInterceptorChain.java:106)
	at org.junit.jupiter.engine.execution.InvocationInterceptorChain.proceed(InvocationInterceptorChain.java:64)
	at org.junit.jupiter.engine.execution.InvocationInterceptorChain.chainAndInvoke(InvocationInterceptorChain.java:45)
	at org.junit.jupiter.engine.execution.InvocationInterceptorChain.invoke(InvocationInterceptorChain.java:37)
	at org.junit.jupiter.engine.execution.ExecutableInvoker.invoke(ExecutableInvoker.java:104)
	at org.junit.jupiter.engine.execution.ExecutableInvoker.invoke(ExecutableInvoker.java:98)
	at org.junit.jupiter.engine.descriptor.TestMethodTestDescriptor.lambda$invokeTestMethod$6(TestMethodTestDescriptor.java:212)
	at org.junit.platform.engine.support.hierarchical.ThrowableCollector.execute(ThrowableCollector.java:73)
	at org.junit.jupiter.engine.descriptor.TestMethodTestDescriptor.invokeTestMethod(TestMethodTestDescriptor.java:208)
	at org.junit.jupiter.engine.descriptor.TestMethodTestDescriptor.execute(TestMethodTestDescriptor.java:137)
	at org.junit.jupiter.engine.descriptor.TestMethodTestDescriptor.execute(TestMethodTestDescriptor.java:71)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.lambda$executeRecursively$5(NodeTestTask.java:135)
	at org.junit.platform.engine.support.hierarchical.ThrowableCollector.execute(ThrowableCollector.java:73)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.lambda$executeRecursively$7(NodeTestTask.java:125)
	at org.junit.platform.engine.support.hierarchical.Node.around(Node.java:135)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.lambda$executeRecursively$8(NodeTestTask.java:123)
	at org.junit.platform.engine.support.hierarchical.ThrowableCollector.execute(ThrowableCollector.java:73)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.executeRecursively(NodeTestTask.java:122)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.execute(NodeTestTask.java:80)
	at java.base/java.util.ArrayList.forEach(ArrayList.java:1510)
	at org.junit.platform.engine.support.hierarchical.SameThreadHierarchicalTestExecutorService.invokeAll(SameThreadHierarchicalTestExecutorService.java:38)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.lambda$executeRecursively$5(NodeTestTask.java:139)
	at org.junit.platform.engine.support.hierarchical.ThrowableCollector.execute(ThrowableCollector.java:73)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.lambda$executeRecursively$7(NodeTestTask.java:125)
	at org.junit.platform.engine.support.hierarchical.Node.around(Node.java:135)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.lambda$executeRecursively$8(NodeTestTask.java:123)
	at org.junit.platform.engine.support.hierarchical.ThrowableCollector.execute(ThrowableCollector.java:73)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.executeRecursively(NodeTestTask.java:122)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.execute(NodeTestTask.java:80)
	at java.base/java.util.ArrayList.forEach(ArrayList.java:1510)
	at org.junit.platform.engine.support.hierarchical.SameThreadHierarchicalTestExecutorService.invokeAll(SameThreadHierarchicalTestExecutorService.java:38)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.lambda$executeRecursively$5(NodeTestTask.java:139)
	at org.junit.platform.engine.support.hierarchical.ThrowableCollector.execute(ThrowableCollector.java:73)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.lambda$executeRecursively$7(NodeTestTask.java:125)
	at org.junit.platform.engine.support.hierarchical.Node.around(Node.java:135)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.lambda$executeRecursively$8(NodeTestTask.java:123)
	at org.junit.platform.engine.support.hierarchical.ThrowableCollector.execute(ThrowableCollector.java:73)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.executeRecursively(NodeTestTask.java:122)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.execute(NodeTestTask.java:80)
	at org.junit.platform.engine.support.hierarchical.SameThreadHierarchicalTestExecutorService.submit(SameThreadHierarchicalTestExecutorService.java:32)
	at org.junit.platform.engine.support.hierarchical.HierarchicalTestExecutor.execute(HierarchicalTestExecutor.java:57)
	at org.junit.platform.engine.support.hierarchical.HierarchicalTestEngine.execute(HierarchicalTestEngine.java:51)
	at org.junit.platform.launcher.core.DefaultLauncher.execute(DefaultLauncher.java:248)
	at org.junit.platform.launcher.core.DefaultLauncher.lambda$execute$5(DefaultLauncher.java:211)
	at org.junit.platform.launcher.core.DefaultLauncher.withInterceptedStreams(DefaultLauncher.java:226)
	at org.junit.platform.launcher.core.DefaultLauncher.execute(DefaultLauncher.java:199)
	at org.junit.platform.launcher.core.DefaultLauncher.execute(DefaultLauncher.java:132)
	at com.intellij.junit5.JUnit5IdeaTestRunner.startRunnerWithArgs(JUnit5IdeaTestRunner.java:71)
	at com.intellij.rt.junit.IdeaTestRunner$Repeater.startRunnerWithArgs(IdeaTestRunner.java:33)
	at com.intellij.rt.junit.JUnitStarter.prepareStreamsAndStart(JUnitStarter.java:220)
	at com.intellij.rt.junit.JUnitStarter.main(JUnitStarter.java:53)
Caused by: org.h2.jdbc.JdbcSQLDataException: Data conversion error converting "UUID to JSON"
Data conversion error converting "UUID to JSON"; SQL statement:
select json_object(key ? value "PARENT"."ID", key ? value "PARENT"."NAME", key ? value json_arrayagg(json_object(key ? value "CHILD"."PARENT_ID", key ? value "CHILD"."NAME") order by "PARENT"."NAME")) from "PARENT" left outer join "CHILD" on "CHILD"."PARENT_ID" = "PARENT"."ID" group by "PARENT"."ID", "PARENT"."NAME" order by "PARENT"."ID", "PARENT"."NAME" [22018-200]
	at org.h2.message.DbException.getJdbcSQLException(DbException.java:457)
	at org.h2.message.DbException.getJdbcSQLException(DbException.java:429)
	at org.h2.message.DbException.get(DbException.java:205)
	at org.h2.message.DbException.get(DbException.java:181)
	at org.h2.value.Value.getDataConversionError(Value.java:1504)
	at org.h2.value.Value.convertToJson(Value.java:1439)
	at org.h2.value.Value.convertTo(Value.java:861)
	at org.h2.value.Value.convertTo(Value.java:737)
	at org.h2.expression.function.Function.jsonObjectAppend(Function.java:2368)
	at org.h2.expression.function.Function.jsonObject(Function.java:2351)
	at org.h2.expression.function.Function.getSimpleValue(Function.java:1153)
	at org.h2.expression.function.Function.getValueWithArgs(Function.java:1274)
	at org.h2.expression.function.Function.getValue(Function.java:672)
	at org.h2.expression.aggregate.Aggregate.updateAggregate(Aggregate.java:205)
	at org.h2.expression.aggregate.AbstractAggregate.updateAggregate(AbstractAggregate.java:280)
	at org.h2.expression.analysis.DataAnalysisOperation.updateAggregate(DataAnalysisOperation.java:252)
	at org.h2.expression.function.Function.updateAggregate(Function.java:3049)
	at org.h2.command.dml.Select.updateAgg(Select.java:545)
	at org.h2.command.dml.Select.gatherGroup(Select.java:525)
	at org.h2.command.dml.Select.queryGroup(Select.java:487)
	at org.h2.command.dml.Select.queryWithoutCache(Select.java:839)
	at org.h2.command.dml.Query.queryWithoutCacheLazyCheck(Query.java:201)
	at org.h2.command.dml.Query.query(Query.java:489)
	at org.h2.command.dml.Query.query(Query.java:451)
	at org.h2.command.CommandContainer.query(CommandContainer.java:285)
	at org.h2.command.Command.executeQuery(Command.java:195)
	at org.h2.jdbc.JdbcPreparedStatement.execute(JdbcPreparedStatement.java:233)
	at org.jooq.tools.jdbc.DefaultPreparedStatement.execute(DefaultPreparedStatement.java:214)
	at org.jooq.impl.Tools.executeStatementAndGetFirstResultSet(Tools.java:4186)
	at org.jooq.impl.AbstractResultQuery.execute(AbstractResultQuery.java:279)
	at org.jooq.impl.AbstractQuery.execute(AbstractQuery.java:375)
	... 79 more
```

Btw the same kind of problem seems to happen to OffsetDateTime record fields (TIMESTAMP WITH TIME ZONE in database):
```
org.springframework.dao.DataIntegrityViolationException: jOOQ; SQL [select json_object(key ? value "PARENT"."ID", key ? value "PARENT"."NAME", key ? value "PARENT"."CREATED_AT", key ? value json_arrayagg(json_object(key ? value "CHILD"."PARENT_ID", key ? value "CHILD"."NAME") order by "PARENT"."NAME")) from "PARENT" left outer join "CHILD" on "CHILD"."PARENT_ID" = "PARENT"."ID" group by "PARENT"."ID", "PARENT"."NAME" order by "PARENT"."ID", "PARENT"."NAME"]; Data conversion error converting "TIMESTAMP WITH TIME ZONE to JSON"
Data conversion error converting "TIMESTAMP WITH TIME ZONE to JSON"; SQL statement:
select json_object(key ? value "PARENT"."ID", key ? value "PARENT"."NAME", key ? value "PARENT"."CREATED_AT", key ? value json_arrayagg(json_object(key ? value "CHILD"."PARENT_ID", key ? value "CHILD"."NAME") order by "PARENT"."NAME")) from "PARENT" left outer join "CHILD" on "CHILD"."PARENT_ID" = "PARENT"."ID" group by "PARENT"."ID", "PARENT"."NAME" order by "PARENT"."ID", "PARENT"."NAME" [22018-200]; nested exception is org.h2.jdbc.JdbcSQLDataException: Data conversion error converting "TIMESTAMP WITH TIME ZONE to JSON"
Data conversion error converting "TIMESTAMP WITH TIME ZONE to JSON"; SQL statement:
select json_object(key ? value "PARENT"."ID", key ? value "PARENT"."NAME", key ? value "PARENT"."CREATED_AT", key ? value json_arrayagg(json_object(key ? value "CHILD"."PARENT_ID", key ? value "CHILD"."NAME") order by "PARENT"."NAME")) from "PARENT" left outer join "CHILD" on "CHILD"."PARENT_ID" = "PARENT"."ID" group by "PARENT"."ID", "PARENT"."NAME" order by "PARENT"."ID", "PARENT"."NAME" [22018-200]

	at org.jooq_3.14.1.DEFAULT.debug(Unknown Source)
...
```

Should I open another ticket for that?

**Comment by katzyn** [comment]
@lukaseder
Current H2 now supports direct explicit or implicit casts from `UUID`, datetime, and array values to `JSON`, these changes will be included into H2 2.0.202.

**Comment by lukaseder** [comment]
> @gilinykh Should I open another ticket for that?

Thanks, @gilinykh. I'll have another look, soon. If you think this is a slightly different case from the original one, then yes, please open another issue.

> @katzyn Current H2 now supports direct explicit or implicit casts from `UUID`, datetime, and array values to `JSON`, these changes will be included into H2 2.0.202.

Excellent. I obviously prefer a solution in H2 than in jOOQ. You say 2.0.202, does that many any 2.0.201 version is already tagged and available from somewhere? I haven't seen any tags or releases in Maven Central...

**Comment by katzyn** [comment]
No, it isn't. We decided to reserve odd build numbers to development builds, because otherwise sometimes it's hard to say where the exception came from (H2 includes build numbers to error codes).

**Comment by lukaseder** [comment]
> We decided to reserve odd build numbers to development builds, because otherwise sometimes it's hard to say where the exception came from (H2 includes build numbers into error codes).

Reminds me of using `10`, `20`, `30` as line numbers in BASIC 😅
