### ISSUE TITLE
Add support for Oracle associative array of object types as IN parameter

### ISSUE THREAD

**Issue by satri14** [jOOQ/jOOQ#13957]
### Actual behavior

Getting record type no supported in Oracle Dialect:

```sql
Procedure ABC
(
      x_rec                            IN  T.x_rec
,     a_tbl            				   IN  T.a_tbl
,     b_tbl           				   IN  T.b_tbl
,     c_tbl            				   IN  T.c_tbl
,     x_chrid                          OUT NOCOPY Number
,     x_return_status                  OUT NOCOPY VARCHAR2
,     x_msg_count                      OUT NOCOPY Number
,     x_msg_data                       OUT NOCOPY VARCHAR2
)

Type a_tbl is TABLE of CC_type index by binary_integer; 
```

```java
     public class ATblRecord extends AssociativeArrayRecordImpl<Integer, CCTypeRecord> {


     		ATblRecord(){
     		 super(Apps.APPS, XX.AA, "CC_TYPE",
            com.example.springbootdemo.xxx.udt.ContactType.CC_TYPE.getDataType(),
            SQLDataType.INTEGER);
     		}
     }
```

Calling method:
++++++++++++++++++++

```java
 TTT.create(configuration, xrec, new ATblRecord(), new BTblRecord(),
        new CTblRecord());
```

<img width="468" alt="image" src="https://user-images.githubusercontent.com/99150935/188196012-ac33001c-dbd5-405e-b4ff-3614b5d4621b.png">
<img width="1741" alt="image" src="https://user-images.githubusercontent.com/99150935/188196299-e69bebd1-1881-49dd-8116-af04415aa751.png">

Ref: https://stackoverflow.com/questions/73574574/getting-sqldialectnotsupportedexception-not-supported-by-dialect-type-class

Error:

```
2022-09-02 12:18:21.960  WARN 27112 --- [nio-9193-exec-4] .S.o.j.e.SQLDialectNotSupportedException : Not supported by dialect : Type class com.example.springbootjooqdemo.jooq.sample.model.apps.packages.oks_contracts_pub.udt.records.ContactTblRecord is not supported in dialect ORACLE21C
2022-09-02 12:18:21.963 ERROR 27112 --- [nio-9193-exec-4] o.a.c.c.C.[.[.[/].[dispatcherServlet]    : Servlet.service() for servlet [dispatcherServlet] in context with path [] threw exception [Request processing failed; nested exception is org.jooq.exception.DataAccessException: SQL [null]; Error while writing value at JDBC bind index: 68] with root cause

org.jooq.exception.SQLDialectNotSupportedException: Type class com.example.springbootjooqdemo.jooq.sample.model.apps.packages.TTT.T.records.TblRecord is not supported in dialect ORACLE21C
	at org.jooq.impl.DefaultDataType.getDataType(DefaultDataType.java:835) ~[jooq-3.17.3.jar:na]
	at org.jooq.impl.DefaultDataType.getDataType(DefaultDataType.java:779) ~[jooq-3.17.3.jar:na]
	at org.jooq.impl.DefaultBinding$DefaultOtherBinding.set0(DefaultBinding.java:3561) ~[jooq-3.17.3.jar:na]
	at org.jooq.impl.DefaultBinding$InternalBinding.set(DefaultBinding.java:1010) ~[jooq-3.17.3.jar:na]
	at org.jooq.impl.DefaultBindContext.bindValue0(DefaultBindContext.java:63) ~[jooq-3.17.3.jar:na]
	at org.jooq.impl.AbstractBindContext.bindValue(AbstractBindContext.java:74) ~[jooq-3.17.3.jar:na]
	at org.jooq.impl.AssociativeArrayConstant.bind0(AssociativeArrayConstant.java:120) ~[jooq-3.17.3.jar:na]
	at org.jooq.impl.AssociativeArrayConstant.accept(AssociativeArrayConstant.java:84) ~[jooq-3.17.3.jar:na]
	at org.jooq.impl.AbstractBindContext.bindInternal(AbstractBindContext.java:258) ~[jooq-3.17.3.jar:na]
	at org.jooq.impl.AbstractBindContext.visit0(AbstractBindContext.java:68) ~[jooq-3.17.3.jar:na]
	at org.jooq.impl.AbstractContext.visit(AbstractContext.java:340) ~[jooq-3.17.3.jar:na]
	at org.jooq.impl.AbstractContext.visit(AbstractContext.java:254) ~[jooq-3.17.3.jar:na]
	at org.jooq.impl.AbstractRoutine.bind1(AbstractRoutine.java:717) ~[jooq-3.17.3.jar:na]
	at org.jooq.impl.AbstractRoutine.bind0(AbstractRoutine.java:662) ~[jooq-3.17.3.jar:na]
	at org.jooq.impl.AbstractRoutine.accept(AbstractRoutine.java:612) ~[jooq-3.17.3.jar:na]
	at org.jooq.impl.AbstractBindContext.bindInternal(AbstractBindContext.java:258) ~[jooq-3.17.3.jar:na]
	at org.jooq.impl.AbstractBindContext.visit0(AbstractBindContext.java:68) ~[jooq-3.17.3.jar:na]
	at org.jooq.impl.AbstractContext.visit(AbstractContext.java:340) ~[jooq-3.17.3.jar:na]
	at org.jooq.impl.AbstractRoutine.executeCallableStatement(AbstractRoutine.java:549) ~[jooq-3.17.3.jar:na]
	at org.jooq.impl.AbstractRoutine.execute(AbstractRoutine.java:386) ~[jooq-3.17.3.jar:na]
	at org.jooq.impl.Tools.attach(Tools.java:1518) ~[jooq-3.17.3.jar:na]
	at org.jooq.impl.AbstractRoutine.execute(AbstractRoutine.java:366) ~[jooq-3.17.3.jar:na]
	at com.example.springbootjooqdemo.jooq.sample.model.apps.packages.OksContractsPub.createContractHeader(OksContractsPub.java:156) ~[classes/:na]
	at com.example.springbootjooqdemo.SpringBootJooqDemoApplication.createContractHeader(SpringBootJooqDemoApplication.java:99) ~[classes/:na]
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[na:na]
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[na:na]
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[na:na]
	at java.base/java.lang.reflect.Method.invoke(Method.java:566) ~[na:na]
	at org.springframework.web.method.support.InvocableHandlerMethod.doInvoke(InvocableHandlerMethod.java:205) ~[spring-web-5.3.22.jar:5.3.22]
	at org.springframework.web.method.support.InvocableHandlerMethod.invokeForRequest(InvocableHandlerMethod.java:150) ~[spring-web-5.3.22.jar:5.3.22]
	at org.springframework.web.servlet.mvc.method.annotation.ServletInvocableHandlerMethod.invokeAndHandle(ServletInvocableHandlerMethod.java:117) ~[spring-webmvc-5.3.22.jar:5.3.22]
	at org.springframework.web.servlet.mvc.method.annotation.RequestMappingHandlerAdapter.invokeHandlerMethod(RequestMappingHandlerAdapter.java:895) ~[spring-webmvc-5.3.22.jar:5.3.22]
	at org.springframework.web.servlet.mvc.method.annotation.RequestMappingHandlerAdapter.handleInternal(RequestMappingHandlerAdapter.java:808) ~[spring-webmvc-5.3.22.jar:5.3.22]
	at org.springframework.web.servlet.mvc.method.AbstractHandlerMethodAdapter.handle(AbstractHandlerMethodAdapter.java:87) ~[spring-webmvc-5.3.22.jar:5.3.22]
	at org.springframework.web.servlet.DispatcherServlet.doDispatch(DispatcherServlet.java:1070) ~[spring-webmvc-5.3.22.jar:5.3.22]
	at org.springframework.web.servlet.DispatcherServlet.doService(DispatcherServlet.java:963) ~[spring-webmvc-5.3.22.jar:5.3.22]
	at org.springframework.web.servlet.FrameworkServlet.processRequest(FrameworkServlet.java:1006) ~[spring-webmvc-5.3.22.jar:5.3.22]
	at org.springframework.web.servlet.FrameworkServlet.doPost(FrameworkServlet.java:909) ~[spring-webmvc-5.3.22.jar:5.3.22]
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:681) ~[tomcat-embed-core-9.0.65.jar:4.0.FR]
	at org.springframework.web.servlet.FrameworkServlet.service(FrameworkServlet.java:883) ~[spring-webmvc-5.3.22.jar:5.3.22]
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:764) ~[tomcat-embed-core-9.0.65.jar:4.0.FR]
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:227) ~[tomcat-embed-core-9.0.65.jar:9.0.65]
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:162) ~[tomcat-embed-core-9.0.65.jar:9.0.65]
	at org.apache.tomcat.websocket.server.WsFilter.doFilter(WsFilter.java:53) ~[tomcat-embed-websocket-9.0.65.jar:9.0.65]
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:189) ~[tomcat-embed-core-9.0.65.jar:9.0.65]
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:162) ~[tomcat-embed-core-9.0.65.jar:9.0.65]
	at org.springframework.web.filter.RequestContextFilter.doFilterInternal(RequestContextFilter.java:100) ~[spring-web-5.3.22.jar:5.3.22]
	at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:117) ~[spring-web-5.3.22.jar:5.3.22]
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:189) ~[tomcat-embed-core-9.0.65.jar:9.0.65]
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:162) ~[tomcat-embed-core-9.0.65.jar:9.0.65]
	at org.springframework.web.filter.FormContentFilter.doFilterInternal(FormContentFilter.java:93) ~[spring-web-5.3.22.jar:5.3.22]
	at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:117) ~[spring-web-5.3.22.jar:5.3.22]
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:189) ~[tomcat-embed-core-9.0.65.jar:9.0.65]
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:162) ~[tomcat-embed-core-9.0.65.jar:9.0.65]
	at org.springframework.web.filter.CharacterEncodingFilter.doFilterInternal(CharacterEncodingFilter.java:201) ~[spring-web-5.3.22.jar:5.3.22]
	at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:117) ~[spring-web-5.3.22.jar:5.3.22]
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:189) ~[tomcat-embed-core-9.0.65.jar:9.0.65]
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:162) ~[tomcat-embed-core-9.0.65.jar:9.0.65]
	at org.apache.catalina.core.StandardWrapperValve.invoke(StandardWrapperValve.java:197) ~[tomcat-embed-core-9.0.65.jar:9.0.65]
	at org.apache.catalina.core.StandardContextValve.invoke(StandardContextValve.java:97) ~[tomcat-embed-core-9.0.65.jar:9.0.65]
	at org.apache.catalina.authenticator.AuthenticatorBase.invoke(AuthenticatorBase.java:541) ~[tomcat-embed-core-9.0.65.jar:9.0.65]
	at org.apache.catalina.core.StandardHostValve.invoke(StandardHostValve.java:135) ~[tomcat-embed-core-9.0.65.jar:9.0.65]
	at org.apache.catalina.valves.ErrorReportValve.invoke(ErrorReportValve.java:92) ~[tomcat-embed-core-9.0.65.jar:9.0.65]
	at org.apache.catalina.core.StandardEngineValve.invoke(StandardEngineValve.java:78) ~[tomcat-embed-core-9.0.65.jar:9.0.65]
	at org.apache.catalina.connector.CoyoteAdapter.service(CoyoteAdapter.java:360) ~[tomcat-embed-core-9.0.65.jar:9.0.65]
	at org.apache.coyote.http11.Http11Processor.service(Http11Processor.java:399) ~[tomcat-embed-core-9.0.65.jar:9.0.65]
	at org.apache.coyote.AbstractProcessorLight.process(AbstractProcessorLight.java:65) ~[tomcat-embed-core-9.0.65.jar:9.0.65]
	at org.apache.coyote.AbstractProtocol$ConnectionHandler.process(AbstractProtocol.java:890) ~[tomcat-embed-core-9.0.65.jar:9.0.65]
	at org.apache.tomcat.util.net.NioEndpoint$SocketProcessor.doRun(NioEndpoint.java:1789) ~[tomcat-embed-core-9.0.65.jar:9.0.65]
	at org.apache.tomcat.util.net.SocketProcessorBase.run(SocketProcessorBase.java:49) ~[tomcat-embed-core-9.0.65.jar:9.0.65]
	at org.apache.tomcat.util.threads.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1191) ~[tomcat-embed-core-9.0.65.jar:9.0.65]
	at org.apache.tomcat.util.threads.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:659) ~[tomcat-embed-core-9.0.65.jar:9.0.65]
	at org.apache.tomcat.util.threads.TaskThread$WrappingRunnable.run(TaskThread.java:61) ~[tomcat-embed-core-9.0.65.jar:9.0.65]
	at java.base/java.lang.Thread.run(Thread.java:829) ~[na:na]
```

### Steps to reproduce the problem

Please follow through the sample PL/SQL to reproduce the error.

### jOOQ Version

3.17.3

### Database product and version

Oracle19C Enterprise Edition

### Java Version

JDK 11

### JDBC driver name and version (include name if unofficial driver)

ojdbc8

**Comment by lukaseder** [comment]
Thanks a lot for your report. I will look into this shortly.

**Comment by lukaseder** [comment]
Thanks again. I can reproduce this. Will look into a fix, now

**Comment by lukaseder** [comment]
It seems that our integration tests have covered associative arrays of objects only as `OUT` types, not as `IN` types, which is why this flaw has gone unnoticed. Obviously, both directions should be supported.

**Comment by lukaseder** [comment]
Hm, it seems that this simply isn't supported yet. I can't find an issue that documents this current lack of support, though.

**Comment by bharatps** [comment]
Hello Lukas, 

Would you be able to give us a time frame on the fix. We were about to make a purchase as this is probably the single most important reason for us to consider JOOQ. We are in the process of converting all our custom Oracle ERP APIs into java APIs and we have a whole lot of them which needs to be dealt with urgently. 

Appreciate your inputs on this.

**Comment by lukaseder** [comment]
We'll definitely make it a high priority for jOOQ 3.18, which should ship by the end of Q4 2022 or Q1 2023 (there's usually no promise in release dates, but snapshot builds can be accessed early on from here: https://www.jooq.org/download/versions)

A quick workaround would be to add auxiliary API where you split your associative array into two parts, e.g.:

```sql
CREATE TYPE o AS OBJECT (...);

-- Auxiliary types
CREATE TYPE i AS TABLE OF NUMBER;
CREATE TYPE t AS TABLE OF o;

CREATE PACKAGE p AS
  TYPE pls_t IS TABLE OF o INDEX BY binary_integer;

  -- Your actual procedure
  PROCEDURE ABC (t pls_t);

  -- Your auxiliary procedure
  PROCEDURE ABC_AUX (i i, t t);
END P;
/
```

The auxiliary procedure would then loop over both tables and create an associative array from them, which it then passes to the actual procedure. Chances are, that you don't actually need the associative array, in case of which you don't need the `i` type.

**Comment by bharatps** [comment]
Thank you so much for the update.

**Comment by satri14** [comment]
Thanks Lukas for looking into this issue, for now I managed this case and handled it JDBC but we would like to review JooQ for our all our use case. Please keep us posted if there is any patch you would like us to try and test if release early. Again thank you.!

**Comment by lukaseder** [comment]
> for now I managed this case and handled it with JDBC

How did you do this specifically? Using ojdbc API? Can you show an example? That would certainly speed things up...

> Please keep us posted if there is any patch you would like us to try and test if released early. Again thank you.!

You can subscribe to this issue to get notifications.

**Comment by satri14** [comment]
Sure Lukas happy to help, please refer the below example:
+++++++++++++++++++++++++++++++

@Repository
@Slf4j
public class CreateRepository {

  @PersistenceContext
  EntityManager _entityManager;

  private final String A = "A";
  private final String B = "B";
  private final String C = "C";
  private final String D = "D";

  public void create(T t) throws SQLException, ClassNotFoundException {
    EntityManagerFactoryInfo _entityManagerFactoryInfo =
        (EntityManagerFactoryInfo) _entityManager.getEntityManagerFactory();
    Connection _connection = _entityManagerFactoryInfo.getDataSource().getConnection();

    Map connectionTypeMap = _connection.getTypeMap();
    connectionTypeMap.put(A, Class.forName(A.class.getName()));
    connectionTypeMap.put(B, Class.forName(B.class.getName()));
    connectionTypeMap.put(C, Class.forName(C.class.getName()));
    connectionTypeMap.put(D, Class.forName(D.class.getName()));
    _connection.setTypeMap(connectionTypeMap);

    CallableStatement callableStatement =
        _connection.prepareCall("{call X.TTT.CREATE(?, ?, ?, ?, ?, ?, ?, ?)}");

    try (Connection hikariCon = _connection) {
      if (hikariCon.isWrapperFor(OracleConnection.class)) {

        OracleConnection oracleConnection = hikariCon.unwrap(OracleConnection.class);

        C[] cTypeArray = new C[0];
        
        Array cTable = oracleConnection.createARRAY("TTT.C", cTypeArray);

        B[] bArr = new B[0];
        
        Array bTable =
            oracleConnection.createARRAY("TTT.B", bArr);
        
        A[] aArr = new A[0];

        Array aTable =
            oracleConnection.createARRAY("TTT.A", aArr);

        callableStatement.setObject(1, t);
        callableStatement.setArray(2, cTable);
        callableStatement.setArray(3, bTable);
        callableStatement.setArray(4, aTable);
        callableStatement.registerOutParameter(5, Types.INTEGER);
        callableStatement.registerOutParameter(6, Types.VARCHAR);
        callableStatement.registerOutParameter(7, Types.INTEGER);
        callableStatement.registerOutParameter(8, Types.VARCHAR);

        callableStatement.execute();
        }
    } catch (Exception e) {
      logger.error(e.getMessage(), e);
    }
  }
}

**Comment by lukaseder** [comment]
Oh, I see, you're just passing the associative array values, not the indexes as well. This issue here aims for passing both...

Anyway, as promised, I'll look into this soon, starting from tomorrow. It should definitely be a lot easier on Oracle 19c than it used to be.

**Comment by lukaseder** [comment]
I think I got this working for `INDEX BY binary_integer` types. The same approach you've mentioned won't work for `INDEX BY varchar2` types, as far as I can tell. I'm getting:

```
Caused by: java.sql.SQLException: invalid n ame pattern: TEST.PLS_OBJECTS.PLS_ASSOC_V_O
	at oracle.jdbc.oracore.OracleTypeADT.initMetadata12(OracleTypeADT.java:626)
	at oracle.jdbc.oracore.OracleTypeADT.initMetadata(OracleTypeADT.java:562)
	at oracle.jdbc.oracore.OracleTypeADT.init(OracleTypeADT.java:491)
	at oracle.sql.ArrayDescriptor.initPickler(ArrayDescriptor.java:1725)
	at oracle.sql.ArrayDescriptor.<init>(ArrayDescriptor.java:387)
	at oracle.sql.ArrayDescriptor.<init>(ArrayDescriptor.java:363)
	at oracle.sql.ArrayDescriptor.createDescriptor(ArrayDescriptor.java:223)
	at oracle.sql.ArrayDescriptor.createDescriptor(ArrayDescriptor.java:108)
	at oracle.jdbc.driver.PhysicalConnection.createARRAY(PhysicalConnection.java:7338)
	at org.jooq.impl.DefaultBinding$AbstractArrayOrAssociativeArrayRecordBinding.createOracleARRAY(DefaultBinding.java:1531)
	at org.jooq.impl.DefaultBinding$AbstractArrayOrAssociativeArrayRecordBinding.lambda$0(DefaultBinding.java:1465)
	at org.jooq.impl.DefaultExecuteContext.lambda$4(DefaultExecuteContext.java:243)
	at org.jooq.impl.DefaultExecuteContext.localExecuteContext(DefaultExecuteContext.java:254)
	at org.jooq.impl.DefaultExecuteContext.localExecuteContext(DefaultExecuteContext.java:243)
	at org.jooq.impl.DefaultBinding$AbstractArrayOrAssociativeArrayRecordBinding.set0(DefaultBinding.java:1465)
	at org.jooq.impl.DefaultBinding$AbstractArrayOrAssociativeArrayRecordBinding.set0(DefaultBinding.java:1)
	at org.jooq.impl.DefaultBinding$InternalBinding.set(DefaultBinding.java:1019)
```

I'll try working around that next week, possibly destructuring the associative array for `IN` parameters just like we currently do for `OUT` parameters.

The next 3.18.0-SNAPSHOT version will include the logic:
https://www.jooq.org/download/versions

Please let me know (by email, to sales@datageekery.com) if you wish to sign up for an extended trial to test that, starting from next week.

**Comment by bharatps** [comment]
This is great Lukas. Appreciate your inputs so much.

**Comment by satri14** [comment]
Good to know it worked for you. Well I notice we do have some use cases around INDEX BY VARCHAR2 so it might still be an issue as far as I foresee especially for those use cases based on your error logs. Please keep us posted if you have any luck with it. Nevertheless I will give it a try with the new version and will drop an email if needed for extended trial, Thanks.

**Comment by lukaseder** [comment]
> Well I notice we do have some use cases around INDEX BY VARCHAR2 so it might still be an issue as far as I foresee especially for those use cases based on your error logs

How do you bind those to ojdbc?

**Comment by satri14** [comment]
Lukas,

Please refer below:

Oracle JDBC drivers directly support PL/SQL scalar index-by tables with numeric or character elements. An index-by table with numeric elements can be mapped to the following Java array types:

int[]

double[]

float[]

java.math.BigDecimal[]

oracle.sql.NUMBER[]

An index-by table with character elements can be mapped to the following Java array types:

String[]

oracle.sql.CHAR[]

In the following circumstances, you must convey certain information for an index-by table type, as described:

Whenever you use the index-by table type in an OUT or IN OUT parameter, you must specify the maximum number of elements, which is otherwise optional. You can specify the maximum number of elements using the customary syntax for Java array allocation. For example, you could specify int[100] to denote a type that can accommodate up to 100 elements or oracle.sql.CHAR[20] for up to 20 elements.

For index-by tables with character elements, you can optionally specify the maximum size of an individual element, in bytes. This setting is defined using the SQL-like size syntax. For example, for an index-by table used for IN arguments, you could specify String[](30). You could also specify oracle.sql.CHAR[20](255) for an index-by table of maximum length 20, the elements of which will not exceed 255 bytes each.

Refer:
https://docs.oracle.com/cd/E18283_01/java.112/e10587/datamap.htm#i1005939

**Comment by lukaseder** [comment]
Note, my question isn't about the table *value type*, but about the table *key type*

That page says:

> The limitation of mapping PL/SQL index-by table to an array is that the table must be indexed by integer.

Though, it's from Oracle 11g, so I wager things have improved a bit in the meantime. But I still couldn't find any way to map `indexed by varchar` tables. But as always, I'll find a way eventually, e.g. by manually destructuring the table into its component types.

**Comment by satri14** [comment]
> The next 3.18.0-SNAPSHOT version will include the logic:
> https://www.jooq.org/download/versions

I don't see this snapshot is available for download under Free Trial, could you please check.

**Comment by lukaseder** [comment]
The free trial doesn't have access to snapshot builds. Are you interested in an extended trial? If so, can you please reach out to sales@datageekery.com to get a license key?

**Comment by bharatps** [comment]
Hello Lukas, we have requested our Vendor onboarding team to reach out to
you ***@***.***) requesting for the same. We will be initiating
a purchase process and so would request your immediate help for the same.

Thanks & Regards,
-Bharat

**Comment by lukaseder** [comment]
> Hello Lukas, we have requested our Vendor onboarding team to reach out to you ***@***.***) requesting for the same. We will be initiating a purchase process and so would request your immediate help for the same.

Perfect, thank you. I've sent an extended trial license key, which you can use to test the latest 3.18.0-SNAPSHOT version.

**Comment by satri14** [comment]
@lukaseder : Any update on index by 

> Though, it's from Oracle 11g, so I wager things have improved a bit in the meantime. But I still couldn't find any way to map `indexed by varchar` tables. But as always, I'll find a way eventually, e.g. by manually destructuring the table into its component types.

@lukaseder : Lukas, any update on this, do we have any timelines for this.

**Comment by satri14** [comment]
@lukaseder we are noticing that one of our package is taking 1 hr 42 min for code generation.. we have 100's of these packages in our DB, do you think if there is anything we might need to consider ?

**Comment by lukaseder** [comment]
> @lukaseder : Lukas, any update on this, do we have any timelines for this.

Thanks for your patience. There's no timeline for this. It is a high priority for jOOQ 3.18, due for late Q4 2022 / early Q1 2023. What are you blocked with, specifically?

1. Have you tried using the `indexed by pls_integer` support, does it work for you?
2. Have you tried working with the mentioned workarounds on your end, i.e. adding auxiliary procedures / functions that work with SQL types, rather than PL/SQL types?

> @lukaseder we are noticing that one of our package is taking 1 hr 42 min for code generation.. we have 100's of these packages in our DB, do you think if there is anything we might need to consider ?

Can you open a new issue for this, please? It's probably possible to speed things up, but that's not related to associative arrays.

**Comment by lukaseder** [comment]
Regarding the `indexed by varchar` support, I can definitely speed up (as in: deliver this week) simple associative arrays where the value type is a scalar type, as opposed to an object/table/record type. That should probably already help with 70% of all associative arrays that are `indexed by varchar`.

Supporting more complex associative array values might take longer to implement, if we have to destructure them.

**Comment by lukaseder** [comment]
I've looked a bit more deeply into a possible implementation for the destructuring of arbitrary associative array types as procedure `IN` (or `IN OUT`) parameters. It seems that the same approach as we've already implemented in 2021 can work here as well. For details, see: https://github.com/jOOQ/jOOQ/issues/5620#issuecomment-885647930

I've pushed a draft that will be included in the next nightly build (3.18.0-SNAPSHOT). Will look into supporting more complex cases. Current integration tests will support:

```sql
CREATE TYPE u_book_type AS OBJECT (
  id number(7),
  title varchar2(400)
);

CREATE OR REPLACE PACKAGE test.pls_objects AS
  TYPE pls_r_t IS RECORD (a NUMBER);

  TYPE pls_assoc_i_n IS TABLE OF NUMBER        INDEX BY PLS_INTEGER;
  TYPE pls_assoc_i_v IS TABLE OF VARCHAR2(50)  INDEX BY PLS_INTEGER;
  TYPE pls_assoc_i_r IS TABLE OF pls_r_t       INDEX BY PLS_INTEGER;
  TYPE pls_assoc_i_o IS TABLE OF u_book_type   INDEX BY PLS_INTEGER;
  TYPE pls_assoc_v_n IS TABLE OF NUMBER        INDEX BY VARCHAR2(50);
  TYPE pls_assoc_v_v IS TABLE OF VARCHAR2(50)  INDEX BY VARCHAR2(50);
  TYPE pls_assoc_v_r IS TABLE OF pls_r_t       INDEX BY VARCHAR2(50);
  TYPE pls_assoc_v_o IS TABLE OF u_book_type   INDEX BY VARCHAR2(50);
  -- [...]

  FUNCTION f_io_assoc_i_n (p_i pls_assoc_i_n, p_io in out pls_assoc_i_n) RETURN pls_assoc_i_n;
  FUNCTION f_io_assoc_i_v (p_i pls_assoc_i_v, p_io in out pls_assoc_i_v) RETURN pls_assoc_i_v;
  FUNCTION f_io_assoc_i_r (p_i pls_assoc_i_r, p_io in out pls_assoc_i_r) RETURN pls_assoc_i_r;
  FUNCTION f_io_assoc_i_o (p_i pls_assoc_i_o, p_io in out pls_assoc_i_o) RETURN pls_assoc_i_o;
  FUNCTION f_io_assoc_v_n (p_i pls_assoc_v_n, p_io in out pls_assoc_v_n) RETURN pls_assoc_v_n;
  FUNCTION f_io_assoc_v_v (p_i pls_assoc_v_v, p_io in out pls_assoc_v_v) RETURN pls_assoc_v_v;
  FUNCTION f_io_assoc_v_r (p_i pls_assoc_v_r, p_io in out pls_assoc_v_r) RETURN pls_assoc_v_r;
  FUNCTION f_io_assoc_v_o (p_i pls_assoc_v_o, p_io in out pls_assoc_v_o) RETURN pls_assoc_v_o;
  -- [...]
END;
```

Additional integration tests will include (both indexed by `pls_integer` and `varchar`):

- `TABLE OF` nested record types
- `TABLE OF` nested object types
- `TABLE OF` SQL table types (not sure if this can be done)
- `TABLE OF` PL/SQL table types (not sure if this can be done)
- Combinations of the above

**Comment by lukaseder** [comment]
Implemented in jOOQ 3.18.0. More edge cases will be handled in https://github.com/jOOQ/jOOQ/issues/5620

**Comment by satri14** [comment]
I just tried similar original example with latest 3.18.0-SNAPSHOT and still getting the below error:
++++++++++++++++++++++++++++++++++

2022-09-21 19:24:24.492 ERROR 37405 --- [nio-9193-exec-1] o.a.c.c.C.[.[.[/].[dispatcherServlet]    : Servlet.service() for servlet [dispatcherServlet] in context with path [] threw exception [Request processing failed; nested exception is org.jooq.exception.DataAccessException: SQL [declare "r1"

PL/SQL: Statement ignored

	at oracle.jdbc.driver.T4CTTIoer11.processError(T4CTTIoer11.java:637) ~[ojdbc11-21.5.0.0.jar:21.5.0.0.0]
	at oracle.jdbc.driver.T4CTTIoer11.processError(T4CTTIoer11.java:564) ~[ojdbc11-21.5.0.0.jar:21.5.0.0.0]
	at oracle.jdbc.driver.T4C8Oall.processError(T4C8Oall.java:1231) ~[ojdbc11-21.5.0.0.jar:21.5.0.0.0]
	at oracle.jdbc.driver.T4CTTIfun.receive(T4CTTIfun.java:772) ~[ojdbc11-21.5.0.0.jar:21.5.0.0.0]
	at oracle.jdbc.driver.T4CTTIfun.doRPC(T4CTTIfun.java:299) ~[ojdbc11-21.5.0.0.jar:21.5.0.0.0]
	at oracle.jdbc.driver.T4C8Oall.doOALL(T4C8Oall.java:512) ~[ojdbc11-21.5.0.0.jar:21.5.0.0.0]
	at oracle.jdbc.driver.T4CCallableStatement.doOall8(T4CCallableStatement.java:159) ~[ojdbc11-21.5.0.0.jar:21.5.0.0.0]
	at oracle.jdbc.driver.T4CCallableStatement.executeForRows(T4CCallableStatement.java:1237) ~[ojdbc11-21.5.0.0.jar:21.5.0.0.0]
	at oracle.jdbc.driver.OracleStatement.executeSQLStatement(OracleStatement.java:1820) ~[ojdbc11-21.5.0.0.jar:21.5.0.0.0]
	at oracle.jdbc.driver.OracleStatement.doExecuteWithTimeout(OracleStatement.java:1472) ~[ojdbc11-21.5.0.0.jar:21.5.0.0.0]
	at oracle.jdbc.driver.OraclePreparedStatement.executeInternal(OraclePreparedStatement.java:3761) ~[ojdbc11-21.5.0.0.jar:21.5.0.0.0]
	at oracle.jdbc.driver.OraclePreparedStatement.execute(OraclePreparedStatement.java:4136) ~[ojdbc11-21.5.0.0.jar:21.5.0.0.0]
	at oracle.jdbc.driver.OracleCallableStatement.execute(OracleCallableStatement.java:4279) ~[ojdbc11-21.5.0.0.jar:21.5.0.0.0]
	at oracle.jdbc.driver.OraclePreparedStatementWrapper.execute(OraclePreparedStatementWrapper.java:1014) ~[ojdbc11-21.5.0.0.jar:21.5.0.0.0]
	at org.jooq.tools.jdbc.DefaultPreparedStatement.execute(DefaultPreparedStatement.java:219) ~[jooq-3.18.0-SNAPSHOT.jar:na]
	at org.jooq.impl.Tools.executeStatementAndGetFirstResultSet(Tools.java:4529) ~[jooq-3.18.0-SNAPSHOT.jar:na]
	at org.jooq.impl.AbstractRoutine.execute0(AbstractRoutine.java:598) ~[jooq-3.18.0-SNAPSHOT.jar:na]
	at org.jooq.impl.AbstractRoutine.executeCallableStatement(AbstractRoutine.java:558) ~[jooq-3.18.0-SNAPSHOT.jar:na]
	at org.jooq.impl.AbstractRoutine.execute(AbstractRoutine.java:391) ~[jooq-3.18.0-SNAPSHOT.jar:na]
	at org.jooq.impl.Tools.attach(Tools.java:1558) ~[jooq-3.18.0-SNAPSHOT.jar:na]
	at org.jooq.impl.AbstractRoutine.execute(AbstractRoutine.java:371) ~[jooq-3.18.0-SNAPSHOT.jar:na]

**Comment by lukaseder** [comment]
Thanks, @satri14. Can you please show what you did exactly, including:

- The signature of the package and all the types involved
- The exact way you called the procedure

These things cannot be derived from the stack trace alone.

Do note that as I've mentioned here https://github.com/jOOQ/jOOQ/issues/13957#issuecomment-1253537845, nested record and nested object types aren't yet handled correctly and will be supported soon, via #5620

**Comment by lukaseder** [comment]
Also, your comment was made 7 hours ago, did you already use the latest snapshot version (currently 20220922003256)?

**Comment by satri14** [comment]
> Also, your comment was made 7 hours ago, did you already use the latest snapshot version (currently 20220922003256)?
> 20220922003256


Though we took the latest Java 11 versions, May I know which Java 11 version snapshot you would like us to try ?

**Comment by lukaseder** [comment]
Always the latest, as snapshots get continued improvements.

**Comment by satri14** [comment]
> Always the latest, as snapshots get continued improvements.

For Java 11 : Is this the right snapshot 20220922113001 as of today you want us try as I wanted to make sure it has the fix ?

**Comment by lukaseder** [comment]
I'm not sure what you mean by "the fix?"

You just posted a stack trace. I don't know how to reproduce it, nor if it is even related to this feature request here.

When you open a new issue via https://github.com/jOOQ/jOOQ/issues/new/choose, we usually ask for reproduction steps, which help reproduce the issue. It will make sure we'll be discussing the same thing. I've closed this issue here, because as far as I can tell, the feature has been implemented. The latest Java 11 snapshot build has the timestamp 20220922154732, so it is newer than what you were using. This includes fixes for nested records in associative arrays, as well as boolean types.

But again, perhaps your stack trace isn't really related to this?

**Comment by satri14** [comment]
> I'm not sure what you mean by "the fix?"

I am referring to the original issue raised for this ticket (#13957) with the example and full stack trace I shared clearly defining the ask of supporting the complex Record Type as per the original ticket. You said you have fixed it from your comments (mentioned below #2) based on the JDBC example I shared.

(#2)
> I think I got this working for INDEX BY binary_integer types. The same approach you've mentioned won't work for INDEX BY varchar2 types, as far as I can tell. I'm getting:

> Thanks again. I can reproduce this. Will look into a fix, now
Also you mentioned you have reproduced the error and mentioned about the fix. Please see your comments. 
All I am asking is if you have fixed it what is the version # for this fix so that we can test it.

Please let me know if any of this is not clear.

**Comment by lukaseder** [comment]
I can try it again, tomorrow, though I'll have to make assumptions. Your example is missing some details. E.g.

```sql
Procedure ABC -- Is this a package procedure or standalone procedure
(
      x_rec                            IN  T.x_rec -- What's T? What's x_rec
,     a_tbl            				   IN  T.a_tbl -- Is this the below table type?
,     b_tbl           				   IN  T.b_tbl -- What's this?
,     c_tbl            				   IN  T.c_tbl -- What's this?
,     x_chrid                          OUT NOCOPY Number
,     x_return_status                  OUT NOCOPY VARCHAR2
,     x_msg_count                      OUT NOCOPY Number
,     x_msg_data                       OUT NOCOPY VARCHAR2
)

Type a_tbl is TABLE of CC_type index by binary_integer; -- What's CC_type?
```

Then your call:

```java
// What's TTT? Is that the package, but above, it looked as though it was named T
// What's create? Is that the ABC procedure?
// Does it make sense
 TTT.create(configuration, xrec, new ATblRecord(), new BTblRecord(),
        new CTblRecord());
```

I can obviously try to make assumptions and try to reproduce things, but often, this won't lead to results. Without knowing all the types, I can't tell you whether:

- There's still a bug
- There's a limitation which isn't implemented, and probably can't be (e.g. nesting table types in table types)
- There's a usage error

All the while noting that prior to the implementation of this issue, associative arrays weren't supported as `IN` parameters *at all*, while now, they're supported but there are some limitations as mentioned here https://github.com/jOOQ/jOOQ/issues/5620.

**Comment by lukaseder** [comment]
Thanks for the additional info, @satri14. I'll try reproducing this again, but I don't see much else other than what I've already assumed and integration tested so far. Ideally, a fully self contained reproducer would be the most helpful approach in such cases. Typically, this approach works:

- Create a dedicated package containing only the procedures and types to reproduce a problem
- Remove all things that aren't necessary to reproducing the problem

This would help create a "minimal, complete, verifiable example" (we have a template for this at https://github.com/jOOQ/jOOQ-mcve). While it does seem like a little extra effort up front, it's usually much faster in helping ensure a problem is reproducible.

Nevertheless, I'll try again to see if types similar to yours can already help reproduce the problem,  this afternoon.

**Comment by lukaseder** [comment]
Regarding an earlier issue:

> > @lukaseder we are noticing that one of our package is taking 1 hr 42 min for code generation.. we have 100's of these packages in our DB, do you think if there is anything we might need to consider ?
> 
> Can you open a new issue for this, please? It's probably possible to speed things up, but that's not related to associative arrays.

I've been investigating a few performance related issues this morning, and could identify at least these 2:

- https://github.com/jOOQ/jOOQ/issues/14014
- https://github.com/jOOQ/jOOQ/issues/14017

If you're interested in me investigating this further for your case, I'd be happy to have a look if you can create a new issue.

**Comment by lukaseder** [comment]
So, I've created this package:

```sql
create or replace package t as 
  type cc_type is record (
    x1 varchar2(30),
    y1 varchar2(30),
    z1 varchar2(30),
    zz1 number
  );

  type a_tbl is table of cc_type index by binary_integer;
  type b_tbl is table of cc_type index by varchar2(50);

  procedure abc (
    a_tbl IN t.a_tbl,
    b_tbl IN t.b_tbl,
    x_chrid out nocopy number,
    x_return_status out nocopy varchar2,
    x_msg_count out nocopy number,
    x_msg_data out nocopy varchar2
  );
end t;

create or replace package body t as
  procedure abc (
    a_tbl IN t.a_tbl,
    b_tbl IN t.b_tbl,
    x_chrid out nocopy number,
    x_return_status out nocopy varchar2,
    x_msg_count out nocopy number,
    x_msg_data out nocopy varchar2
  ) is
  begin
    x_chrid := a_tbl.count + b_tbl.count;
  end; 
end t;
```

Re-generated code to get this package representation:

```java
public class T extends PackageImpl {

    private static final long serialVersionUID = 1L;

    /**
     * The reference instance of <code>TEST.T</code>
     */
    public static final T T = new T();

    /**
     * Call <code>TEST.T.ABC</code>
     */
    public static Abc abc(
          Configuration configuration
        , ATblRecord aTbl
        , BTblRecord bTbl
    ) {
        Abc p = new Abc();
        p.setATbl(aTbl);
        p.setBTbl(bTbl);

        p.execute(configuration);
        return p;
    }

    /**
     * No further instances allowed
     */
    private T() {
        super("T", Test.TEST);
    }
}
```

Along with:

```java
public class ATblRecord extends AssociativeArrayRecordImpl<Integer, CcTypeRecord> {

    private static final long serialVersionUID = 1L;

    /**
     * Create a new <code>TEST.T.A_TBL</code> record
     */
    public ATblRecord() {
        super(Test.TEST, T.T, "A_TBL", org.jooq.test.oracle.generatedclasses.test.packages.t.udt.CcType.CC_TYPE.getDataType(), SQLDataType.INTEGER);
    }
}

public class BTblRecord extends AssociativeArrayRecordImpl<String, CcTypeRecord> {

    private static final long serialVersionUID = 1L;

    /**
     * Create a new <code>TEST.T.B_TBL</code> record
     */
    public BTblRecord() {
        super(Test.TEST, T.T, "B_TBL", org.jooq.test.oracle.generatedclasses.test.packages.t.udt.CcType.CC_TYPE.getDataType(), SQLDataType.VARCHAR);
    }
}

public class CcTypeRecord extends UDTRecordImpl<CcTypeRecord> {

    private static final long serialVersionUID = 1L;

    /**
     * Setter for <code>TEST.T.CC_TYPE.X1</code>.
     */
    public void setX1(String value) {
        set(0, value);
    }

    /**
     * Getter for <code>TEST.T.CC_TYPE.X1</code>.
     */
    public String getX1() {
        return (String) get(0);
    }

    /**
     * Setter for <code>TEST.T.CC_TYPE.Y1</code>.
     */
    public void setY1(String value) {
        set(1, value);
    }

    /**
     * Getter for <code>TEST.T.CC_TYPE.Y1</code>.
     */
    public String getY1() {
        return (String) get(1);
    }

    /**
     * Setter for <code>TEST.T.CC_TYPE.Z1</code>.
     */
    public void setZ1(String value) {
        set(2, value);
    }

    /**
     * Getter for <code>TEST.T.CC_TYPE.Z1</code>.
     */
    public String getZ1() {
        return (String) get(2);
    }

    /**
     * Setter for <code>TEST.T.CC_TYPE.ZZ1</code>.
     */
    public void setZz1(BigDecimal value) {
        set(3, value);
    }

    /**
     * Getter for <code>TEST.T.CC_TYPE.ZZ1</code>.
     */
    public BigDecimal getZz1() {
        return (BigDecimal) get(3);
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached CcTypeRecord
     */
    public CcTypeRecord() {
        super(CcType.CC_TYPE);
    }

    /**
     * Create a detached, initialised CcTypeRecord
     */
    public CcTypeRecord(String x1, String y1, String z1, BigDecimal zz1) {
        super(CcType.CC_TYPE);

        setX1(x1);
        setY1(y1);
        setZ1(z1);
        setZz1(zz1);
    }

    /**
     * Create a detached, initialised CcTypeRecord
     */
    public CcTypeRecord(org.jooq.test.oracle.generatedclasses.test.packages.t.udt.pojos.CcType value) {
        super(CcType.CC_TYPE);

        if (value != null) {
            setX1(value.getX1());
            setY1(value.getY1());
            setZ1(value.getZ1());
            setZz1(value.getZz1());
        }
    }
}
```

I then ran this call:

```java
ATblRecord a = new ATblRecord();
BTblRecord b = new BTblRecord();
a.put(1, new CcTypeRecord("a", "b", "c", BigDecimal.ONE));
b.put("a", new CcTypeRecord("a", "b", "c", BigDecimal.ONE));
Abc r1 = T.abc(configuration, a, b);
System.out.println(r1.getXChrid());
```

It produced this output:

```
13:53:36,350 DEBUG [LoggerListener                ] - Calling routine          : declare "a1" "TEST"."T"."A_TBL"; "e1" number(10); "i1" pls_integer := 1; "k1" DBMS_SQL.NUMBER_TABLE; "v11" DBMS_SQL.VARCHAR2_TABLE; "v12" DBMS_SQL.VARCHAR2_TABLE; "v13" DBMS_SQL.VARCHAR2_TABLE; "v14" DBMS_SQL.NUMBER_TABLE; "a2" "TEST"."T"."B_TBL"; "e2" varchar2(4000); "i2" pls_integer := 1; "k2" DBMS_SQL.VARCHAR2_TABLE; "v21" DBMS_SQL.VARCHAR2_TABLE; "v22" DBMS_SQL.VARCHAR2_TABLE; "v23" DBMS_SQL.VARCHAR2_TABLE; "v24" DBMS_SQL.NUMBER_TABLE; begin "k1" := ?; "v11" := ?; "v12" := ?; "v13" := ?; "v14" := ?; for "i" in "k1".first .. "k1".last loop "a1"("k1"("i")) := TEST.T.CC_TYPE("v11"("i"), "v12"("i"), "v13"("i"), "v14"("i")); end loop; "k2" := ?; "v21" := ?; "v22" := ?; "v23" := ?; "v24" := ?; for "i" in "k2".first .. "k2".last loop "a2"("k2"("i")) := TEST.T.CC_TYPE("v21"("i"), "v22"("i"), "v23"("i"), "v24"("i")); end loop; "TEST"."T"."ABC" ("A_TBL" => "a1", "B_TBL" => "a2", "X_CHRID" => ?, "X_RETURN_STATUS" => ?, "X_MSG_COUNT" => ?, "X_MSG_DATA" => ?); end;
13:53:36,641 DEBUG [LoggerListener                ] - Fetched OUT parameters   : +-------+---------------+-----------+----------+
13:53:36,642 DEBUG [LoggerListener                ] -                          : |X_CHRID|X_RETURN_STATUS|X_MSG_COUNT|X_MSG_DATA|
13:53:36,642 DEBUG [LoggerListener                ] -                          : +-------+---------------+-----------+----------+
13:53:36,642 DEBUG [LoggerListener                ] -                          : |      2|{null}         |     {null}|{null}    |
13:53:36,642 DEBUG [LoggerListener                ] -                          : +-------+---------------+-----------+----------+
2
```

So, as expected?

**Comment by lukaseder** [comment]
OK, I see. You sent empty records, which should be supported as well of course:

```java
ATblRecord a = new ATblRecord();
BTblRecord b = new BTblRecord();
Abc r1 = T.abc(configuration, a, b);
System.out.println(r1.getXChrid());
```

This currently produces:

```
13:54:56,696 DEBUG [LoggerListener                ] - Calling routine          : declare "a1" "TEST"."T"."A_TBL"; "e1" number(10); "i1" pls_integer := 1; "k1" DBMS_SQL.NUMBER_TABLE; "v11" DBMS_SQL.VARCHAR2_TABLE; "v12" DBMS_SQL.VARCHAR2_TABLE; "v13" DBMS_SQL.VARCHAR2_TABLE; "v14" DBMS_SQL.NUMBER_TABLE; "a2" "TEST"."T"."B_TBL"; "e2" varchar2(4000); "i2" pls_integer := 1; "k2" DBMS_SQL.VARCHAR2_TABLE; "v21" DBMS_SQL.VARCHAR2_TABLE; "v22" DBMS_SQL.VARCHAR2_TABLE; "v23" DBMS_SQL.VARCHAR2_TABLE; "v24" DBMS_SQL.NUMBER_TABLE; begin "k1" := ?; "v11" := ?; "v12" := ?; "v13" := ?; "v14" := ?; for "i" in "k1".first .. "k1".last loop "a1"("k1"("i")) := TEST.T.CC_TYPE("v11"("i"), "v12"("i"), "v13"("i"), "v14"("i")); end loop; "k2" := ?; "v21" := ?; "v22" := ?; "v23" := ?; "v24" := ?; for "i" in "k2".first .. "k2".last loop "a2"("k2"("i")) := TEST.T.CC_TYPE("v21"("i"), "v22"("i"), "v23"("i"), "v24"("i")); end loop; "TEST"."T"."ABC" ("A_TBL" => "a1", "B_TBL" => "a2", "X_CHRID" => ?, "X_RETURN_STATUS" => ?, "X_MSG_COUNT" => ?, "X_MSG_DATA" => ?); end;
13:54:56,984 DEBUG [LoggerListener                ] - Exception                
org.jooq.exception.DataAccessException: SQL [declare "a1" "TEST"."T"."A_TBL"; "e1" number(10); "i1" pls_integer := 1; "k1" DBMS_SQL.NUMBER_TABLE; "v11" DBMS_SQL.VARCHAR2_TABLE; "v12" DBMS_SQL.VARCHAR2_TABLE; "v13" DBMS_SQL.VARCHAR2_TABLE; "v14" DBMS_SQL.NUMBER_TABLE; "a2" "TEST"."T"."B_TBL"; "e2" varchar2(4000); "i2" pls_integer := 1; "k2" DBMS_SQL.VARCHAR2_TABLE; "v21" DBMS_SQL.VARCHAR2_TABLE; "v22" DBMS_SQL.VARCHAR2_TABLE; "v23" DBMS_SQL.VARCHAR2_TABLE; "v24" DBMS_SQL.NUMBER_TABLE; begin "k1" := ?; "v11" := ?; "v12" := ?; "v13" := ?; "v14" := ?; for "i" in "k1".first .. "k1".last loop "a1"("k1"("i")) := TEST.T.CC_TYPE("v11"("i"), "v12"("i"), "v13"("i"), "v14"("i")); end loop; "k2" := ?; "v21" := ?; "v22" := ?; "v23" := ?; "v24" := ?; for "i" in "k2".first .. "k2".last loop "a2"("k2"("i")) := TEST.T.CC_TYPE("v21"("i"), "v22"("i"), "v23"("i"), "v24"("i")); end loop; "TEST"."T"."ABC" ("A_TBL" => "a1", "B_TBL" => "a2", "X_CHRID" => ?, "X_RETURN_STATUS" => ?, "X_MSG_COUNT" => ?, "X_MSG_DATA" => ?); end;]; ORA-06502: PL/SQL: numerischer oder Wertefehler
ORA-06512: in Zeile 1

	at org.jooq_3.18.0-SNAPSHOT.ORACLE21C.debug(Unknown Source) ~[?:?]
	at org.jooq.impl.Tools.translate(Tools.java:3358) ~[classes/:?]
	at org.jooq.impl.DefaultExecuteContext.sqlException(DefaultExecuteContext.java:686) ~[classes/:?]
	at org.jooq.impl.AbstractRoutine.executeCallableStatement(AbstractRoutine.java:586) ~[classes/:?]
	at org.jooq.impl.AbstractRoutine.execute(AbstractRoutine.java:390) ~[classes/:?]
	at org.jooq.impl.Tools.attach(Tools.java:1576) ~[classes/:?]
	at org.jooq.impl.AbstractRoutine.execute(AbstractRoutine.java:370) ~[classes/:?]
	at org.jooq.test.oracle.generatedclasses.test.packages.T.abc(T.java:40) ~[test-classes/:?]
	at org.jooq.testscripts.JDBC.main(JDBC.java:72) ~[test-classes/:?]
Caused by: java.sql.SQLException: ORA-06502: PL/SQL: numerischer oder Wertefehler
ORA-06512: in Zeile 1

	at oracle.jdbc.driver.T4CTTIoer11.processError(T4CTTIoer11.java:630) ~[ojdbc11-21.5.0.0.jar:21.5.0.0.0]
	at oracle.jdbc.driver.T4CTTIoer11.processError(T4CTTIoer11.java:564) ~[ojdbc11-21.5.0.0.jar:21.5.0.0.0]
	at oracle.jdbc.driver.T4C8Oall.processError(T4C8Oall.java:1231) ~[ojdbc11-21.5.0.0.jar:21.5.0.0.0]
	at oracle.jdbc.driver.T4CTTIfun.receive(T4CTTIfun.java:772) ~[ojdbc11-21.5.0.0.jar:21.5.0.0.0]
	at oracle.jdbc.driver.T4CTTIfun.doRPC(T4CTTIfun.java:299) ~[ojdbc11-21.5.0.0.jar:21.5.0.0.0]
	at oracle.jdbc.driver.T4C8Oall.doOALL(T4C8Oall.java:512) ~[ojdbc11-21.5.0.0.jar:21.5.0.0.0]
	at oracle.jdbc.driver.T4CCallableStatement.doOall8(T4CCallableStatement.java:159) ~[ojdbc11-21.5.0.0.jar:21.5.0.0.0]
	at oracle.jdbc.driver.T4CCallableStatement.executeForRows(T4CCallableStatement.java:1237) ~[ojdbc11-21.5.0.0.jar:21.5.0.0.0]
	at oracle.jdbc.driver.OracleStatement.executeSQLStatement(OracleStatement.java:1820) ~[ojdbc11-21.5.0.0.jar:21.5.0.0.0]
	at oracle.jdbc.driver.OracleStatement.doExecuteWithTimeout(OracleStatement.java:1472) ~[ojdbc11-21.5.0.0.jar:21.5.0.0.0]
	at oracle.jdbc.driver.OraclePreparedStatement.executeInternal(OraclePreparedStatement.java:3761) ~[ojdbc11-21.5.0.0.jar:21.5.0.0.0]
	at oracle.jdbc.driver.OraclePreparedStatement.execute(OraclePreparedStatement.java:4136) ~[ojdbc11-21.5.0.0.jar:21.5.0.0.0]
	at oracle.jdbc.driver.OracleCallableStatement.execute(OracleCallableStatement.java:4279) ~[ojdbc11-21.5.0.0.jar:21.5.0.0.0]
	at oracle.jdbc.driver.OraclePreparedStatementWrapper.execute(OraclePreparedStatementWrapper.java:1014) ~[ojdbc11-21.5.0.0.jar:21.5.0.0.0]
	at org.jooq.tools.jdbc.DefaultPreparedStatement.execute(DefaultPreparedStatement.java:219) ~[classes/:?]
	at org.jooq.impl.Tools.executeStatementAndGetFirstResultSet(Tools.java:4547) ~[classes/:?]
	at org.jooq.impl.AbstractRoutine.execute0(AbstractRoutine.java:597) ~[classes/:?]
	at org.jooq.impl.AbstractRoutine.executeCallableStatement(AbstractRoutine.java:557) ~[classes/:?]
	... 5 more
Caused by: oracle.jdbc.OracleDatabaseException: ORA-06502: PL/SQL: numerischer oder Wertefehler
ORA-06512: in Zeile 1

	at oracle.jdbc.driver.T4CTTIoer11.processError(T4CTTIoer11.java:637) ~[ojdbc11-21.5.0.0.jar:21.5.0.0.0]
	at oracle.jdbc.driver.T4CTTIoer11.processError(T4CTTIoer11.java:564) ~[ojdbc11-21.5.0.0.jar:21.5.0.0.0]
	at oracle.jdbc.driver.T4C8Oall.processError(T4C8Oall.java:1231) ~[ojdbc11-21.5.0.0.jar:21.5.0.0.0]
	at oracle.jdbc.driver.T4CTTIfun.receive(T4CTTIfun.java:772) ~[ojdbc11-21.5.0.0.jar:21.5.0.0.0]
	at oracle.jdbc.driver.T4CTTIfun.doRPC(T4CTTIfun.java:299) ~[ojdbc11-21.5.0.0.jar:21.5.0.0.0]
	at oracle.jdbc.driver.T4C8Oall.doOALL(T4C8Oall.java:512) ~[ojdbc11-21.5.0.0.jar:21.5.0.0.0]
	at oracle.jdbc.driver.T4CCallableStatement.doOall8(T4CCallableStatement.java:159) ~[ojdbc11-21.5.0.0.jar:21.5.0.0.0]
	at oracle.jdbc.driver.T4CCallableStatement.executeForRows(T4CCallableStatement.java:1237) ~[ojdbc11-21.5.0.0.jar:21.5.0.0.0]
	at oracle.jdbc.driver.OracleStatement.executeSQLStatement(OracleStatement.java:1820) ~[ojdbc11-21.5.0.0.jar:21.5.0.0.0]
	at oracle.jdbc.driver.OracleStatement.doExecuteWithTimeout(OracleStatement.java:1472) ~[ojdbc11-21.5.0.0.jar:21.5.0.0.0]
	at oracle.jdbc.driver.OraclePreparedStatement.executeInternal(OraclePreparedStatement.java:3761) ~[ojdbc11-21.5.0.0.jar:21.5.0.0.0]
	at oracle.jdbc.driver.OraclePreparedStatement.execute(OraclePreparedStatement.java:4136) ~[ojdbc11-21.5.0.0.jar:21.5.0.0.0]
	at oracle.jdbc.driver.OracleCallableStatement.execute(OracleCallableStatement.java:4279) ~[ojdbc11-21.5.0.0.jar:21.5.0.0.0]
	at oracle.jdbc.driver.OraclePreparedStatementWrapper.execute(OraclePreparedStatementWrapper.java:1014) ~[ojdbc11-21.5.0.0.jar:21.5.0.0.0]
	at org.jooq.tools.jdbc.DefaultPreparedStatement.execute(DefaultPreparedStatement.java:219) ~[classes/:?]
	at org.jooq.impl.Tools.executeStatementAndGetFirstResultSet(Tools.java:4547) ~[classes/:?]
	at org.jooq.impl.AbstractRoutine.execute0(AbstractRoutine.java:597) ~[classes/:?]
	at org.jooq.impl.AbstractRoutine.executeCallableStatement(AbstractRoutine.java:557) ~[classes/:?]
	... 5 more
6502
ORA-06502: PL/SQL: numerischer oder Wertefehler
ORA-06512: in Zeile 1
```

**Comment by lukaseder** [comment]
A new 3.18.0-SNAPSHOT build is pipelined, and should be published wihtin 1h. I'm not sure though if the error I've seen is the exact same error that you have seen (your error message is truncated, and seems different), so if your error does persist, I'd appreciate a minimal, complete reproducer like the one here: https://github.com/jOOQ/jOOQ/issues/13957#issuecomment-1256116528

**Comment by lukaseder** [comment]
@satri14 have you had a chance to review the latest improvements? Do they work for you?

**Comment by bharatps** [comment]
Hello Lukas,

We are still seeing the same error. Saurabh will get in touch with you to
explain the issue. Would you be able to get on a meeting so we can walk
you through it?

I will have Saurabh coordinate the meeting with you if you are available.

Thanks.
-Bharat

**Comment by lukaseder** [comment]
Yeah, we can try that. Please get in touch at lukas.eder@datageekery.com to schedule a meeting

**Comment by satri14** [comment]
Hey Lukas,

I have setup our call for tomorrow, please review and confirm if the time works for you.

Thanks,
Saurabh

**Comment by lukaseder** [comment]
I didn't receive any invite.

**Comment by lukaseder** [comment]
As discussed by email, the missing thing for you is passing a `null` value as an associative array.

```
java.lang.ClassCastException: class org.jooq.impl.Val cannot be cast to class org.jooq.impl.AssociativeArrayConstant (org.jooq.impl.Val and org.jooq.impl.AssociativeArrayConstant are in unnamed module of loader 'app')
	at org.jooq_3.18.0-SNAPSHOT.ORACLE21C.debug(Unknown Source) ~[?:?]
	at org.jooq.impl.AbstractRoutine.bind1(AbstractRoutine.java:715) ~[classes/:?]
	at org.jooq.impl.AbstractRoutine.bind0(AbstractRoutine.java:668) ~[classes/:?]
	at org.jooq.impl.AbstractRoutine.accept(AbstractRoutine.java:618) ~[classes/:?]
	at org.jooq.impl.AbstractBindContext.bindInternal(AbstractBindContext.java:258) ~[classes/:?]
	at org.jooq.impl.AbstractBindContext.visit0(AbstractBindContext.java:68) ~[classes/:?]
	at org.jooq.impl.AbstractContext.visit(AbstractContext.java:346) ~[classes/:?]
	at org.jooq.impl.AbstractRoutine.executeCallableStatement(AbstractRoutine.java:555) ~[classes/:?]
	at org.jooq.impl.AbstractRoutine.execute(AbstractRoutine.java:392) ~[classes/:?]
	at org.jooq.impl.Tools.attach(Tools.java:1581) ~[classes/:?]
	at org.jooq.impl.AbstractRoutine.execute(AbstractRoutine.java:372) ~[classes/:?]
	at org.jooq.test.oracle.generatedclasses.test.packages.Srb.abc(Srb.java:48) ~[test-classes/:?]
	at org.jooq.testscripts.JDBC.main(JDBC.java:81) ~[test-classes/:?]
Exception in thread "main" java.lang.ClassCastException: class org.jooq.impl.Val cannot be cast to class org.jooq.impl.AssociativeArrayConstant (org.jooq.impl.Val and org.jooq.impl.AssociativeArrayConstant are in unnamed module of loader 'app')
	at org.jooq_3.18.0-SNAPSHOT.ORACLE21C.debug(Unknown Source)
	at org.jooq.impl.AbstractRoutine.bind1(AbstractRoutine.java:715)
	at org.jooq.impl.AbstractRoutine.bind0(AbstractRoutine.java:668)
	at org.jooq.impl.AbstractRoutine.accept(AbstractRoutine.java:618)
	at org.jooq.impl.AbstractBindContext.bindInternal(AbstractBindContext.java:258)
	at org.jooq.impl.AbstractBindContext.visit0(AbstractBindContext.java:68)
	at org.jooq.impl.AbstractContext.visit(AbstractContext.java:346)
	at org.jooq.impl.AbstractRoutine.executeCallableStatement(AbstractRoutine.java:555)
	at org.jooq.impl.AbstractRoutine.execute(AbstractRoutine.java:392)
	at org.jooq.impl.Tools.attach(Tools.java:1581)
	at org.jooq.impl.AbstractRoutine.execute(AbstractRoutine.java:372)
	at org.jooq.test.oracle.generatedclasses.test.packages.Srb.abc(Srb.java:48)
	at org.jooq.testscripts.JDBC.main(JDBC.java:81)
```

But it's not possible in PL/SQL either:

```sql
DECLARE
  TYPE t IS TABLE OF NUMBER INDEX BY PLS_INTEGER;
  PROCEDURE p (i t) IS BEGIN dbms_output.put_line(i.count); END;
BEGIN
  p(null);
END;
```

Producing:

```
SQL Error [6550] [65000]: ORA-06550: line 5, column 5:
PLS-00567: cannot pass NULL to a NOT NULL constrained formal parameter
ORA-06550: line 5, column 3:
PL/SQL: Statement ignored
```

This works:

```sql
DECLARE
  TYPE t IS TABLE OF NUMBER INDEX BY PLS_INTEGER;
  PROCEDURE p (i t) IS BEGIN dbms_output.put_line(i.count); END;
BEGIN
  p(CAST(null as t));
END;
```

But that's just the same as passing an empty table:

```sql
DECLARE
  TYPE t IS TABLE OF NUMBER INDEX BY PLS_INTEGER;
  PROCEDURE p (i t) IS BEGIN dbms_output.put_line(i.count); END;
BEGIN
  p(t());
END;
```

I've created a new issue for this: https://github.com/jOOQ/jOOQ/issues/14097
