### ISSUE TITLE
PostgresDSL arrayOverlap does not properly cast arguments

### ISSUE THREAD

**Issue by ndawg** [jOOQ/jOOQ#14352]
### Expected behavior

Given a table with the following layout:
```sql
create table sample(
  ids text[]
);
```

I expect the `PostgresDSL.arrayOverlap()` method to properly generate a Postgres statement to check for overlapping with a `String[]` variable. For instance, this code:
```java
PostgresDSL.arrayOverlap(SAMPLE.IDS, new String[]{"test"});
```
Should generate the following:
```SQL
"ids" && cast('{"test"}' as text[])
```

### Actual behavior

The `arrayOverlap` method generates the following SQL:
```sql
"ids" && cast('{"test"}' as varchar[])
```
Which causes the following error:
```
ERROR: operator does not exist: text[] && character varying[]
  Hint: No operator matches the given name and argument types. You might need to add explicit type casts.
```

This can be fixed with a custom condition:
```java
private Condition textOverlap(Field<String[]> field, String[] text) {
    return DSL.condition(DSL.sql("{0} && {1}", field, DSL.cast(text, field)));
}
```
But I figured it was worth reporting anyway.

### Steps to reproduce the problem

1. Create a simple database table with a `text[]` column type
2. Attempt to use the `PostgresDSL.arrayOverlap()` method on it
3. Observe the error

### jOOQ Version

3.17.4

### Database product and version

PostgreSQL 11.6 (Debian 11.6-1.pgdg90+1) on x86_64-pc-linux-gnu, compiled by gcc (Debian 6.3.0-18+deb9u1) 6.3.0 20170516, 64-bit

**Comment by lukaseder** [comment]
Thanks for your report. I agree those array functions should be fixed. The issue is similar to this one, which already works: https://github.com/jOOQ/jOOQ/issues/4754

**Comment by rocketraman** [comment]
Also same issue for `PostgresDSL.arrayRemove`. Setting the code generator to force the type of the relevant PostgresQL Text field to `SQLDataType.CLOB` does not solve the problem -- the second String parameter to `arrayRemove` is still interpreted as "character varying":

```
ERROR: function array_remove(text[], character varying) does not exist
```

**Comment by lukaseder** [comment]
Yeah, sure, it's all these array functions

**Comment by rocketraman** [comment]
BTW, this appears to be a suitable workaround for `arrayRemove` (Kotlin syntax):

```
/**
 * Work around https://github.com/jOOQ/jOOQ/issues/14352.
 */
fun arrayRemoveText(array: Field<Array<String>>, element: String): Field<Array<String>> =
  PostgresDSL.arrayRemove(
    array,
    DSL.field(
      DSL.sql("{0}::text", element),
      String::class.java,
    ),
  )
```

**Comment by lukaseder** [comment]
This will be fixed implicitly with https://github.com/jOOQ/jOOQ/issues/11981, specifically the bullet:

> * Deprecate existing `PostgresDSL` methods (i.e. "pull them up")

Once these array functions are pulled up from the `PostgresDSL` to the standard DSL, their implementation will no longer be a plain SQL template, but an ordinary query object model (`QOM`) type, with all the usual functionality where `f(Field<T>, T)` auto-wraps the second argument with the data type of the first, in case of which this should be fixed, implicitly.

I'll proceed with this deprecation of `PostgresDSL` right now.

**Comment by lukaseder** [comment]
Other side effects of moving everything to the standard DSL are:

- Features will be tested with other PG style dialects (e.g. CockroachDB, YugabyteDB)
- Documentation will be added (see e.g. `ARRAY_CONCAT`: https://www.jooq.org/doc/dev/manual/sql-building/column-expressions/array-functions/array-concat-function/)
- The `QueryPart` will be available to the `QOM` transformation API
- Probably more

**Comment by lukaseder** [comment]
Fixed in jOOQ 3.18.0 via https://github.com/jOOQ/jOOQ/issues/11981. Thanks again for your report.
