### ISSUE TITLE
[REACTIVE] DELETE with RETURNING query + Flux + concatMap cause hanging issue

### ISSUE THREAD

**Issue by quantranhong1999** [jOOQ/jOOQ#16055]
### Expected behavior

Given I have a Flux executing a DELETE query with RETURNING, then I use `.concatMap` to continue executing queries upon the returning element should succeed.

### Actual behavior

The reactive chain hangs after `.concatMap` on the first element of the Flux.

### Steps to reproduce the problem

Sample test to reproduce the hang issue (100% hang):

```java
    @Test
    void deleteQueryWithReturningAsFluxAndConcatMapWouldHang() {
        // Setup DSLContext
        Settings jooqSettings = new Settings()
            .withRenderFormatted(true)
            .withStatementType(StatementType.PREPARED_STATEMENT);
        Connection r2dbcConnection = postgresExtension.getConnection().block();
        DSLContext dslContext = DSL.using(r2dbcConnection, SQLDialect.POSTGRES, jooqSettings);

        // Create person table
        Mono.from(dslContext.createTableIfNotExists("person")
                .column("id", SQLDataType.INTEGER.identity(true))
                .column("name", SQLDataType.VARCHAR(50).nullable(false))
                .constraints(DSL.constraint().primaryKey("id")))
            .block();

        // Insert some data into the person table
        BiFunction<Integer, String, Mono<Void>> insertARecordMono = (id, name) -> {
            System.out.println("Inserting user with id " + id + " and name " + name);
            return Mono.from(dslContext.insertInto(DSL.table("person"), DSL.field("id"), DSL.field("name"))
                .values(id, name))
                .then();
        };
        Flux.range(0, 100)
            .flatMap(id -> insertARecordMono.apply(id, "oldName"))
            .then()
            .block();

        // Delete query with returning id, then insert again using Flux.concatMap
        Flux<Integer> deleteQueryWithReturningFlux = Flux.from(dslContext.deleteFrom(DSL.table("person"))
                .where(DSL.field("name").eq("oldName"))
                .returning(DSL.field("id"))) // if We do not use returning here, it would not hang
            .map(record -> record.get(DSL.field("id", Integer.class)));

        deleteQueryWithReturningFlux
            .concatMap(id -> insertARecordMono.apply(id, "newName")) // it hangs upon first Flux element
            .then()
            .block();
    }
```

Some notes:
- If I do not use `.returning` upon the DELETE query, it would not hang
- If I use `deleteQueryWithReturningFlux.flatMap(...)` instead of `deleteQueryWithReturningFlux.concatMap(...)`, it would not hang
- If upon `deleteQueryWithReturningFlux`, if I `.collectList` then it would not hang:
   ```java
        deleteQueryWithReturningFlux
            .collectList()
            .flatMapIterable(Function.identity())
            .concatMap(id -> insertARecordMono.apply(id, "newName")) // it hangs upon first Flux element
            .then()
            .block();
   ```

### jOOQ Version

3.16.23

### Database product and version

PostgreSQL 16.1

### Java Version

openjdk 11

### OS Version

Ubuntu 22.04

### JDBC driver name and version (include name if unofficial driver)

r2dbc-postgresql 1.0.3.RELEASE

**Comment by lukaseder** [comment]
Thanks for your report. Does the issue reproduce with 3.19.1? I'm not sure if all the reactive bugfixes have been backported to the 3.16 branch.

**Comment by quantranhong1999** [comment]
> Does the issue reproduce with 3.19.1? I'm not sure if all the reactive bugfixes have been backported to the 3.16 branch.

I have not tested with 3.19.1 yet (JDK 11 limitation though...). Do you have any plan to backport those reactive bugfixes?

**Comment by lukaseder** [comment]
3.16.22 was the last maintenance release for the 3.16 branch.

**Comment by quantranhong1999** [comment]
> 3.16.22 was the last maintenance release for the 3.16 branch.

Thank you for your information. I hope this will be fixed in the future versions then :-).

**Comment by quantranhong1999** [comment]
Hi, I tried again with jOOQ 3.19.6 and it seems to be still the case.

**Comment by lukaseder** [comment]
Thanks for your message. This issue hasn't been fixed yet, indeed.

**Comment by lukaseder** [comment]
Unfortunately, I have not been able to reproduce your issue at the time, but here's a very similar one that has been fixed in the upcoming 3.20.0, 3.19.13, 3.18.20, 3.17.29 (snapshot builds available from here, tomorrow: https://www.jooq.org/download/versions, or you can build directly from github if you're using the jOOQ Open Source Edition):

- https://github.com/jOOQ/jOOQ/issues/17094

If you have some time to check if any of the above versions fix the issue for you, I'd greatly appreciate your feedback.

**Comment by quantranhong1999** [comment]
Hi,
I tried again with jOOQ 3.19.13 and r2dbc-postgresql 1.0.7.RELEASE and it is still an issue.

**Comment by quantranhong1999** [comment]
Hi,
I tried again with jOOQ 3.19.13 and r2dbc-postgresql 1.0.7.RELEASE and it is still an issue.
