### ISSUE TITLE
 Oracle 12c issue with Multi-Insert into tables with IDENTITY column

### ISSUE THREAD

**Issue by jsauvain** [jOOQ/jOOQ#9074]
### Expected behavior and actual behavior:
Given the following JOOQ Query, it'll produce an ORA-01400 Exception

```java
Field<Integer> foreignKey ...;
InsertValuesStep2<AnyTableRecord, Integer, Double> insertInto = dslContext
	.insertInto(
		ANY_TABLE,
		ANY_TABLE.SOME_FOREIGN_KEY,
		ANY_TABLE.AMOUNT
         );
insertionValues
	.forEach(value -> insertInto.values(foreignKey, val(value.getAmount())));
insertInto.execute();
```
After a bit of analysis it turned out that this query results simplified in something like that:
```sql
insert into ANY_TABLE ("SOME_FOREIGN_KEY", "AMOUNT")
select * from (
  select 123, 50 from dual
)
union all
select * from (
   select 123, 200 from dual
);
```
Given this code it'll throw an ORA-01400 on Oracle 12c
The correct query would be
```sql
insert into ANY_TABLE ("SOME_FOREIGN_KEY", "AMOUNT")
select * from (
  select 123, 50 from dual
  union all
  select 123, 200 from dual
);
```
Additionally it is very interesting that the first query successfully executes on Oracle 18c XE. Maybe you've got an idea why this is the case. 

(Similar Issue #5453)

Thanks in advance

### Versions:

- jOOQ: 3.11.9 PRO
- Java: 8
- Database: Oracle 12c & Oracle 18c XE

**Comment by lukaseder** [comment]
Thank you very much for your report. This does seem exactly like #5453, which should have been fixed in 3.10 already. I wonder what the difference in your case may be, i.e. why the workaround with the additional derived table isn't produced. jOOQ will produce the workaround if your target table contains an identity field, but jOOQ has to know about that.

- What's the DDL definition of the table you're using here?
- What's your code generator configuration?

**Comment by jsauvain** [comment]
Thank you for your response. The Identity field contains the following definition
```java
public final TableField<AnyTableRecord, Integer> MY_PRIMARY_KEY = createField("MY_PRIMARY_KEY", org.jooq.impl.SQLDataType.INTEGER.nullable(false).identity(true), this, "");
```
The Code-Gen happens through H2 which does not seem to be the problem because the identity has been recognized.
Thanks in advance

**Comment by knutwannheden** [comment]
I have tried to reproduce this problem (on Oracle 12c), but in my case both of the `INSERT` statements were accepted. So could you maybe send us the full `CREATE TABLE` statement for your `ANY_TABLE` statement?

**Comment by jsauvain** [comment]
Given this table specification and insertion query it does not work on Oracle 12c
```sql
CREATE TABLE any_other_table (
  my_other_primary_key INT GENERATED ALWAYS AS IDENTITY PRIMARY KEY
);

CREATE TABLE any_table (
  my_primary_key INT GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
  some_foreign_key INT NOT NULL,
  amount NUMBER(32, 20) NOT NULL,
  CONSTRAINT my_foreign_key_const FOREIGN KEY (some_foreign_key) REFERENCES any_other_table (my_other_primary_key)
);

insert into any_other_table (my_other_primary_key) VALUES (DEFAULT);

insert into any_table ("SOME_FOREIGN_KEY", "AMOUNT")
select * from (
  select 123, 50 from dual
)
union all
select * from (
   select 123, 200 from dual
);
```

This results in
` ORA-01400: cannot insert NULL into ...`

**Comment by knutwannheden** [comment]
Thanks for the feedback. It looks like this problem was fixed in some Oracle 12.1 or 12.2 patch, as I cannot reproduce it with my Oracle 12.2 installation. This would also explain why it doesn't cause problems with 18c.

**Comment by jsauvain** [comment]
This seems to be a reasonable cause. We'll look into this possibility and I'll give you feedback in the following days. What I can say for now is that it's not fixed in 12.1.0.2.0. Thanks for your assistance.

**Comment by jsauvain** [comment]
You are right. This Issue was fixed in Oracle 12.2. Will fix this Issue on 12.0/1 or not? Thanks in advance.

**Comment by knutwannheden** [comment]
> You are right. This Issue was fixed in Oracle 12.2. Will you fix this Issue on 12.0/1 or not? Thanks in advance.

If you don't want to upgrade to Oracle 12.2 just because of this annoying bug, we can certainly look into implementing the workaround in jOOQ and include it in a patch release for 3.11 and 3.12.

**Comment by lukaseder** [comment]
We can definitely try to find a workaround for 12.1, perhaps governed by a settings flag. We have a 3.11.13 release scheduled for next week, due to another Oracle related issue. I'll see if we can include a fix for this in that release.

**Comment by jsauvain** [comment]
Unfortunately we do not control the production database. In that case we can't upgrade the database. If you could fix this Issue we would really appreciate it.

**Comment by lukaseder** [comment]
I've had another look at this issue. I can't reproduce the problem with Oracle 18c, 19c or 23ai.

jOOQ 3.20 will deprecate support for Oracle 11g and 12c:

- #17125

Oracle themselves have deprecated support for 12c in 2017, 2 years before this discussion.
